### ISSUE TITLE
"[FATAL tini (16)] exec driver-py failed: No such file or directory" with spark-py:v3.0.0 container image

### ISSUE THREAD

**Issue by akuzni2** [kubeflow/spark-operator#1018]
(Re-)opening this issue as it was previously created but closed [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/908) I'm more than happy to close this one in favor of reopening the other one if someone suggests so. 

Kubernetes version: 1.15.11
Helm version: 3.0.2

**Note**: These same steps were tested with `spark-py-pi.yaml` the 2.4.5 version (spark-py:v2.4.5) and there were no issues.

**Steps to recreate**

1. Create namespace `spark-operator` 
 
2. Install the operator from the [incubator/sparkoperator](https://github.com/helm/charts/tree/master/incubator/sparkoperator) Helm chart. I pulled the chart locally and then ran the below command: 
```
helm upgrade --install spark-operator sparkoperator/ --namespace spark-operator --set sparkJobNamespace=spark-operator --set enableWebhook=true
```
3. Run `pyspark-pi` example:

`spark-py-pi.yaml` definition (note the update to `namespace` field and `serviceAccount`):
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "2"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.0.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.0.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0 
```

Launch Pyspark Application
```
kubectl apply -f spark-py-pi.yaml -n spark-operator
```

4. Check logs:

```
[FATAL tini (16)] exec driver-py failed: No such file or directory
```
