### ISSUE TITLE
Sparkapplication template

### ISSUE THREAD

**Issue by jinxingwang** [kubeflow/spark-operator#1025]
I am interested to contribute something similar to the spark pod template for Sparkapplication.
It can be super useful as a service management standpoint. 
For example:
1: If I want to require all my users to install a Prometheus sidecar so I can collect metrics and monitor them without actively checking every submitted Sparkapplication spec nor team user how to set a Sparkapplication for Prometheus sidecar.
2: Some teams may want to enforce securityContext for every running pod in the cluster for security reasons.
3: adding some pod annotations for service management. 

It is possible to write your own webhook to mutate or validate in order to achieve the above use cases. 
But why not provide this feature within spark operator.

I can think of 2 kinds of templates.
1: default Sparkapplication templates, default if it is not set, or merge if it is a list in the spec.
2: enforce Sparkapplication templates, overwrite user's Sparkapplication.

**Comment by jinxingwang** [comment]
@liyinan926 What do you think?

**Comment by liyinan926** [comment]
That sounds like a good proposal to me. Can you put together a doc on the details? Thanks!

**Comment by jinxingwang** [comment]
new spark operator flag: `--Sparkapplication-default-template`, `--Sparkapplication-overwrite-template` (naming still pending)
Each flag will accept a configmap as input value.
e.g. `--Sparkapplication-default-template=/namespace/configmapName`
The content of the configMap should be a sparkapplication spec.
We can decide fields that is allowed here:
e.g. 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapName
  namespace: namespace
data:
  spec: |
    apiVersion: "sparkoperator.k8s.io/v1beta2"
    kind: ScheduledSparkApplication
    metadata:
      name: spark-pi-scheduled
      namespace: default
    spec:
      schedule: "@every 5m"
      concurrencyPolicy: Allow
      successfulRunHistoryLimit: 1
      failedRunHistoryLimit: 3
      template:
        type: Scala
        mode: cluster
        image: gcr.io/spark/spark:v3.0.0
        mainClass: org.apache.spark.examples.SparkPi
        mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-2.3.0.jar
        driver:
          cores: 1
          memory: 512m
        executor:
          cores: 1
          instances: 1
          memory: 512m
        restartPolicy:
          type: Never
```

Then the sparkOperator will take this spec, and use as the default value for every submitted sparkapplication.

`--Sparkapplication-overwrite-template=/namespace/configmapName`
This flag will be mostly the same, but instead it will overwrite from the input spec to user's submitted sparkapplication.
For lists such as `metadata` `sparkconf` etc in the sparkapplication spec. It should do append on the list. and default/overwrite the keys in the list.
