### ISSUE TITLE
preStop hook got interrupted and graceful termination failed 

### ISSUE THREAD

**Issue by FloraZhang** [kubeflow/spark-operator#1049]
Hi masters,

I'm trying out preStop hook supported by latest spark-operator, and I noticed the preStop hook failed if I run some time-consuming task or simply sleep for a while before pod terminated. The chart spec is the same as in user-guide:
```
spec:
  driver:
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/bash
          - -c
          - touch /var/run/killspark && sleep 65
```

Detailed error message are as below:

```
[root@wzhan-node1 opt]# kubectl describe pod spark-app-driver
  Warning  FailedPreStopHook  1s         kubelet, rob-ha-local-node6  Exec lifecycle hook ([/bin/bash -c touch /var/run/killspark && sleep 65
' exited with 137: , message: ""
```

Starting from stopping driver container, it took about 30s before showing FailedPreStopHook, setting terminationGracePeriodSeconds to 60 sec didn't help either.

Any idea why this is happening?

Thanks,
Wenjing
