### ISSUE TITLE
Example is failed with error /opt/entrypoint.sh: line 40: /tmp/java_opts.txt: Permission denied

### ISSUE THREAD

**Issue by mgorbov** [kubeflow/spark-operator#1078]
Example: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml

Operator values
```
 operatorVersion: v1beta2-1.2.1-3.0.0
imagePullSecrets:
  - name: harbor-credentials
rbac:
  create: true
serviceAccounts:
  spark:
    name: spark
controllerThread: 2
enableWebhook: true
webhookPort: 443
nodeSelector:
  destiny: spark
enableMetrics: true
```

Driver logs
```
++ id -u
+ myuid=185
++ id -g
+ mygid=0
+ set +e
++ getent passwd 185
+ uidentry=
+ set -e
+ '[' -z '' ']'
+ '[' -w /etc/passwd ']'
+ echo '185:x:185:0:anonymous uid:/opt/spark:/bin/false'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
/opt/entrypoint.sh: line 40: /tmp/java_opts.txt: Permission denied
```

**Comment by liyinan926** [comment]
Seems related to https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1056.

**Comment by arun990** [comment]
Hi,
Getting the same error message even though I haven't used volume mounts to /tmp.
kubectl execution of Spark application gets successfully completed when run in default namespace and gives the below error when run in non-default namespace. I do have rbac.yml (having serviceaccount, clusterrole & clusterrolebinding) defined for execution in the non-default namespace.

Pasted the error msg below. Appreciate your advise in overcoming the error.

++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ '[' -z root:x:0:0:root:/root:/bin/bash ']'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
/opt/entrypoint.sh: line 40: /tmp/java_opts.txt: Permission denied

**Comment by arun990** [comment]
Hi, Can someone provide updates on this please to overcome the issue of pemissions denied..

**Comment by chq3272991** [comment]
I met the same problem. When I set "webhook. enable=true", I modified Spark's official Dockerfile, as follows:
# Comment out two line
#ARG spark_uid=185
#USER ${spark_uid}

**Comment by khaledosman1** [comment]
Hi, any solution here?

**Comment by tanlda** [comment]
Any solution, anyone?

Application manifest:
```yaml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-etl
  namespace: sparks
spec:
  type: Python
  mode: cluster
  image: registry.io/spark-etl
  mainApplicationFile: local:///opt/spark/apps/main.py
  sparkVersion: 3.4.0
  driver:
    env:
      - name: PYSPARK_PYTHON
        value: /usr/bin/python3
    labels:
      version: 3.4.0
    podSecurityContext:
      runAsUser: 1000
    volumeMounts:
      - name: spark-work
        mountPath: /mnt/spark/work
  executor:
    labels:
      version: 3.4.0
    podSecurityContext:
      runAsUser: 1000
    volumeMounts:
      - name: spark-data
        mountPath: /mnt/spark/data
      - name: spark-work
        mountPath: /mnt/spark/work
  volumes:
    - name: spark-data
      emptyDir:
        sizeLimit: 5Gi
    - name: spark-work
      emptyDir:
        sizeLimit: 5Gi
```

Dockerfile:
```Dockerfile
FROM apache/spark-py:v3.4.0

USER root

ENV APP_HOME=/opt/spark/apps/

RUN mkdir -p $APP_HOME

WORKDIR $APP_HOME

COPY ./requirements.txt ./requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY ./main.py ./main.py

#USER 185
```

Error:
```
++ id -u
+ myuid=185
++ id -g
+ mygid=0
+ set +e
++ getent passwd 185
+ uidentry=
+ set -e
+ '[' -z '' ']'
+ '[' -w /etc/passwd ']'
+ echo '185:x:185:0:anonymous uid:/opt/spark:/bin/false'
+ '[' -z /opt/java/openjdk ']'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ env
+ grep SPARK_JAVA_OPT_
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
/opt/entrypoint.sh: line 44: java_opts.txt: Permission denied
Stream closed EOF for sparks/spark-etl-driver (spark-kubernetes-driver)
```
