### ISSUE TITLE
Unable to mount secrets as volumes to SparkApplication

### ISSUE THREAD

**Issue by arijitdey** [kubeflow/spark-operator#1086]
Manifest:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: "my-favorite-secret-volume"
      secret:
        secretName: "my-favorite-secret"
        items:
        - key: "api_key"
          path: "api.key"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```
Error:
```
The SparkApplication "spark-pi" is invalid: type: Required value
```

If I comment out, the following line, then the error goes away.
```
#        items:
#        - key: "api_key"
#          path: "api.key"
```
