### ISSUE TITLE
Prometheus operator integration

### ISSUE THREAD

**Issue by nicholas-fwang** [kubeflow/spark-operator#1101]
If we use the `prometheus operator`, we can easily configure the target pod we want to collect metrics for using `pod monitor` crd and label selector and deploy the `prometheus server`.
The approximate spec of the pod monitor is as follows.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: <pod monitor name>
  labels:
    <pod monitor labels for prometheus server>
spec:
  selector:
    matchLabels:
      <pod labels>
  namespaceSelector:
    matchNames:
      - <pod namespace>
  podMetricsEndpoints:
  - port: <container metric port name>
```
```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: <prometheus server name>
spec:
  serviceAccountName: prometheus
  podMonitorSelector:
    matchLabels:
      <pod monitor labels>
  resources:
    <prometheus cpu/memory resources>
  enableAdminAPI: false
```

The spark operator submits the driver and executor pods, and adds a label related to the spark operator to each pod.
If we want to collect spark pod's metric, we need to add `sparkoperator.k8s.io` label to `pod monitor`.
To do this, iteratively we need to looks up the description of the spark pod for filling following values.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: <pod monitor name>
  labels:
    <pod monitor labels for prometheus server>
  ownerReferences:
  - apiVersion: sparkoperator.k8s.io/v1beta2
    controller: true
    kind: SparkApplication
    name: <spark-app-name>
    uid: <spark-app-uid>
spec:
  selector:
    matchLabels:
      sparkoperator.k8s.io/app-name: <spark-app-name>
      spark-role: <spark-role>
      sparkoperator.k8s.io/launched-by-spark-operator: "true"
  namespaceSelector:
    matchNames:
      - <spark namespace>
  podMetricsEndpoints:
  - port: <container metrics port name>
```

So my suggestion is to add a configuration for pod monitor in `spec.monitoring` and create a `pod monitor` in the form below through it.
```yaml
spec:
  monitoring:
  ...
    prometheus:
      ...
      portName: <port-name>
      podMonitor:
        labels:
          <pod monitor labels for prometheus server>
        spark-role: <driver or executor>
```

**Comment by liyinan926** [comment]
The question is how do we support users not using the Prometheus operator.

**Comment by fisache** [comment]
If a user who does not use operator enters the pod monitor spec, a [NoResourceMatchError ](https://godoc.org/k8s.io/apimachinery/pkg/api/meta#NoResourceMatchError) will be raised, the pod monitor creation will be ignored and the spark application will be submitted.

**Comment by fisache** [comment]
@liyinan926 
Hi,
Prometheus operator currently uses kubernetes client version v0.19.2.
In this version, k8s extention api generated code and k8s api machinary library require `context` in all of APIs by [this enhancement](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20200123-client-go-ctx.md)
So, in order to apply the prometheus operator as well as the latest version of other operators, it's required to increase the version of the kubernetes library.
What do you think?

**Comment by guimou** [comment]
Hi!
I've seen that the merge has been done for this, and I can indeed see it the portName feature in the CRD. However, after the CR has been submitted with monitoring like this:
```
monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.12.0.jar"
      port: 8090
      portName: 'tcp-prometheus'
```
portName is listed in the SparkApplication instance, but it is not there in the pod configuration (all the other ports are named, but 8090 is not). Which forces me to use the deprecated "targetPort" in my PodMonitor configuration.
Am I missing something?
