### ISSUE TITLE
Spark Thrift Server(STS) CRD

### ISSUE THREAD

**Issue by nicholas-fwang** [kubeflow/spark-operator#1116]
Spark Thrift Server is a daemon server that can execute spark sql through JDBC/ODBC connector.
It can be usefully used in hive's execution engine and BI tool that supports JDBC/ODBC.

I have deployed thrift server on Kubernetes as below.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: spark-thrift-server
  labels:
    foo: bar
spec:
  containers:
  - name: spark-thrift-server
    image: gcr.io/spark-operator/spark:v3.0.0
    args:
      - /opt/spark/bin/spark-submit
      - --master
      - k8s://https://xx.xx.x.x:443
      - --class
      - org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      - --deploy-mode
      - client
      - --name
      - spark-sql
      - --hiveconf
      - hive.server2.thrift.port 10000
      - --conf
      - spark.executor.instances=1
      - --conf
      - spark.executor.memory=1G
      - --conf
      - spark.driver.memory=1G
      - --conf
      - spark.executor.cores=1
      - --conf
      - spark.kubernetes.namespace=spark-operator
      - --conf
      - spark.kubernetes.container.image=gcr.io/spark-operator/spark:v3.0.0
      - --conf
      - spark.kubernetes.authenticate.driver.serviceAccountName=spark-operator
      - --conf
      - spark.kubernetes.driver.pod.name=spark-thrift-server
    ports:
    - containerPort: 4040
      name: spark-ui
      protocol: TCP
    - containerPort: 10000
      name: spark-thrift
      protocol: TCP
  serviceAccount: spark-operator
  serviceAccountName: spark-operator
---
apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-server
spec:
  clusterIP: None
  ports:
  - name: spark-ui
    port: 4040
    protocol: TCP
    targetPort: 4040
  - name: spark-thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    foo: bar
  sessionAffinity: None
  type: ClusterIP

```

Since STS must be distributed in client mode, the spark operator could not be used directly.
Therefore, it is proposed to create a new CRD and deploy the STS through the spark operator.
Deployment through the spark operator has the following advantages.
- Failover of driver(thrift server)
- Batch Scheduler integration
- Integrated management including monitoring with Spark Application
- Application of various resources of kubernetes using Mutating/Validation webhook

**Comment by ManuelNeubergerWN** [comment]
We had some problem to rewrite this pod into a deployment, but solved it by adding the "spark.kubernetes.driver.pod.name" and "spark.driver.host" to the conf, through enviroment variables. The problem seems to be that otherwise spark.kubernetes.driver.pod.name need to be the name of the created pod AND the service (which is a problem for deployments).
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-thrift-server
  labels:
    foo:: bar
spec:
  replicas: 1
  selector:
    matchLabels:
      foo:: bar
  template:
    metadata:
      labels:
        foo:: bar
    spec:
      containers:
      - name: spark-thrift-server
        image: gcr.io/spark-operator/spark:v3.0.0
        args:
          - /opt/bitnami/spark/bin/spark-submit
          - --master
          - k8s://https://xx.xx.x.x:443
          - --class
          - org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
          - --deploy-mode
          - client
          - --name
          - spark-sql
          - --hiveconf
          - hive.server2.thrift.port 10000
          - --conf
          - spark.executor.instances=1
          - --conf
          - spark.executor.memory=1G
          - --conf
          - spark.driver.memory=1G
          - --conf
          - spark.executor.cores=1
          - --conf
          - spark.kubernetes.namespace=spark-operator
          - --conf
          - spark.kubernetes.container.image=gcr.io/spark-operator/spark:v3.0.0
          - --conf
          - spark.kubernetes.authenticate.driver.serviceAccountName=spark-operator
          - --conf
          - spark.kubernetes.driver.pod.name=$(THRIFT_POD_NAME)
          - --conf
          - spark.driver.bindAddress=$(THRIFT_POD_IP)
          - --conf
          - spark.driver.host=spark-thrift-server
        env:
        - name: THRIFT_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: THRIFT_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 4040
          name: spark-ui
          protocol: TCP    
        - containerPort: 10000
          name: spark-thrift
          protocol: TCP
      serviceAccount: spark-operator
      serviceAccountName: spark-operator
---
apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-server
spec:
  clusterIP: None
  ports:
  - name: spark-ui
    port: 4040
    protocol: TCP
    targetPort: 4040
  - name: spark-thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    foo:: bar
  sessionAffinity: None
  type: ClusterIP
`

**Comment by dnskr** [comment]
Hi @fisache and @ManuelNeubergerWN!

I use `start-thriftserver.sh` to run STS and cannot find a right way to stop it.
This is a part of my code how I start and stop STS:
```yaml
command:
- /bin/sh
- -c
- >
  /opt/spark/sbin/start-thriftserver.sh \
    --name sts \
    --hiveconf hive.server2.thrift.port=10000 \
    --conf spark.driver.host=$(hostname -I) \
    --conf spark.kubernetes.driver.pod.name=$(hostname);
lifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "/opt/spark/sbin/stop-thriftserver.sh > /proc/1/fd/1"]
```
On termination `preStop` hook writes to log the following:
```shell
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.64.0-4+deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
no org.apache.spark.sql.hive.thriftserver.HiveThriftServer2 to stop
```


Do you have any suggestions how this might be solved?
