### ISSUE TITLE
Missing metrics after upgrading to Spark 3.0

### ISSUE THREAD

**Issue by teddyhartanto** [kubeflow/spark-operator#1117]
Hi,

We upgraded our spark cluster to 3.0 a while ago and we realised that a few of the metrics that we were tracking are now no longer being exported (from both the Spark Operator & Spark executors). In particular, we're looking at these metrics:

```
spark_app_executor_failure_count
spark_executor_threadpool_completetasks
spark_executor_shufflebyteswritten_count
spark_executor_shuffleremotebytesread_count
spark_executor_shuffleremotebytesreadtodisk_count
spark_executor_diskbytesspilled_count
spark_executor_threadpool_completetasks
spark_executor_threadpool_activetasks
```

In our `SparkApplication` spec we have this:
```
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/prometheus/jmx_prometheus_javaagent-0.12.0.jar"
      port: 8090
```

We're using `gcr.io/spark-operator/spark-operator:v1beta2-1.1.2-3.0.0` for our spark operator image.

Has anybody faced the same issue?
