### ISSUE TITLE
SparkApplication is scheduled by k8s default-scheduler

### ISSUE THREAD

**Issue by iddelacruz** [kubeflow/spark-operator#1154]
Hi all.

I installed the operator and volcano. Both was installed with Helm 3. The installation was successful. Right now I'm trying to deploy a spark application taked from your examples. 

- k8s server version 1.20
- Volcano version 1.1.2

I'm deploying, but when I enter:  

`kubectl describe [pod_name]`  

this is the result:

```
 Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    21m                default-scheduler  Successfully assigned ...
```

The spark application was scheduled by default_scheduler. 

This is the file:
```

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-job
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "spark:test"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkVersion: "3.0.1"
  batchScheduler: "volcano"
  batchSchedulerOptions:
    queue: "default"
    priorityClassName: "Normal"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"        
    labels:
      version: 3.0.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 3
    memory: "512m"    
    labels:
      version: 3.0.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

Later I installed a normal k8s pod and was scheduled correctly with volcano. Maybe I'm missing some annotations or some properties in the SparkApplication resource type.

Can you help me please. What I'm doing wrong.

**Comment by diskun00** [comment]
Volcano needs to be installed before you install Spark operator. Meanwhile, you can check whether you have configured Spark operator correctly in this [doc](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/volcano-integration.md).

**Comment by shouhong** [comment]
I encounterred the same problem. Volcano was installed before installing Spark operator. I tested the sample SparkApplication in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/volcano-integration.md.  The pod schedulerName for spark-pi-driver is  default-scheduler instead of volcano.

**Comment by iddelacruz** [comment]
Hi, the problem was the properties when I installed the operator. In the integration between volcano and spark operator manual, this is obsolete and the operator installation will be:

`helm install spark-operator spark-operator/spark-operator --namespace spark-operator --set batchScheduler.enable=true --set webhook.enable=true`

And thats it

**Comment by karpoftea** [comment]
@iddelacruz am I right that in order to make volcano schedule spark application it is required:
1. install volcano before spark-operator
2. install spark operator with --set batchScheduler.enable=true --set webhook.enable=true options
3. deploy sparkapplication with batchScheduler: volcano
?

**Comment by karpoftea** [comment]
Actually I have the same problem as mentioned in the very first message :/

Driver application is scheduled by default scheduler:
```
Events:
  Type     Reason       Age   From               Message
  ----     ------       ----  ----               -------
  Normal   Scheduled    39s   default-scheduler  Successfully assigned spark-jobs/spark-pi-scheduled-1626191469985141043-driver to cl1tn6tc3n6di0l966l5-ikib
```

Spark application set to use volcano scheduler, see manifest :
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: spark-pi-scheduled
  namespace: spark-jobs
spec:
  schedule: "51 * * * *"
  concurrencyPolicy: Forbid
  batchScheduler: "volcano"
  template:
    type: Scala
    mode: cluster
### omitted, no specific scheduler properties set
```

volcano is v1.3.0 and installed (before spark-operator) from chart from volcano repo:
```
git clone https://github.com/volcano-sh/volcano.git
    
    cd volcano

    git checkout v1.3.0

    helm install installer/helm/chart/volcano --namespace volcano-system --name-template volcano --set basic.crd_version=v1
```

all volcano pod are running smoothly, no errors 

some logs from volcano-scheduler pod:
```
I0713 15:51:14.310937       1 event_handlers.go:199] Added pod <spark-jobs/spark-pi-scheduled-1626191469985141043-driver> into cache.
I0713 15:51:14.826294       1 cache.go:793] There are <0> Jobs, <1> Queues and <2> Nodes in total for scheduling.
I0713 15:51:14.826610       1 session.go:151] Open Session bcb06995-e7bc-45e0-b2f7-07b5b4bbada0 with <0> Job and <1> Queues
I0713 15:51:14.840953       1 enqueue.go:44] Enter Enqueue ...
I0713 15:51:14.853468       1 enqueue.go:78] Try to enqueue PodGroup to 0 Queues
I0713 15:51:14.853498       1 enqueue.go:102] Leaving Enqueue ...
I0713 15:51:14.853515       1 allocate.go:43] Enter Allocate ...
I0713 15:51:14.853523       1 allocate.go:94] Try to allocate resource to 0 Namespaces
```

spark-operator installed from helm chart:
```
helm install my-release spark-operator/spark-operator \
        --namespace spark-operator \
        --create-namespace \
        --set image.tag=v1beta2-1.2.3-3.1.1 \
        --set sparkJobNamespace=spark-jobs \
        --set webhook.enable=true \
        --set metrics.enable=true \
        --set batchScheduler.enable=true
```

k8s version is 1.19.

Can anyone give a clue where the problem can be?
