### ISSUE TITLE
Spark not reading default conf provided by sparkConfigMap

### ISSUE THREAD

**Issue by pradeeppathak9** [kubeflow/spark-operator#1183]
I have installed spark-operator using Helm Chart with webhook enabled. 
It's working when I set spark configuration using sparkConf, but not when specifying via sparkConfigMap. 

**spark.yaml**
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: consumer-pipeline-v2-consumer-process-2  
  namespace: pipelines
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: registry.digitalocean.com/spoonshot/consumer-pipeline-v2/consumer_process:v0.0.5.test
  imagePullPolicy: Always
  mainApplicationFile: local:///main/main.py
  sparkVersion: "2.4.7"
  sparkConfigMap: consumer-pipeline-v2-config
  
  restartPolicy:
    type: Always

  driver:
    cores: 1
    memory: "1G"
    serviceAccount: spark
    labels:
      version: 2.4.7

  executor:
    cores: 1
    memory: "2G"
    memoryOverhead: "2G"
    instances: 1
    labels:
      version: 2.4.7
```

**configmap.yaml**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-pipeline-v2-config
  namespace: pipelines
data:
  spark-defaults.conf: |
    spark.ui.port=4041
    spark.hadoop.fs.s3a.access.key=cxascascascsacsdcsdc
    spark.hadoop.fs.s3a.secret.key=acsacsacsdacsd+casscasasc
    spark.hadoop.fs.s3a.multipart.size=104857600
```
