### ISSUE TITLE
Not able to mount files in driver pod

### ISSUE THREAD

**Issue by OsamaAnwer** [kubeflow/spark-operator#1184]
Unable to mount files on driver pod.

Below is the sample yaml file I am using

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: Test-Work
  namespace: spark-operator
spec:
  sparkVersion: 3.0.0
  type: Scala
  mode: cluster
  image: "mysparkimage:latest"
  imagePullPolicy: IfNotPresent
  mainClass: HelloWorld
  mainApplicationFile: "local:///home/hadoop/app/lib/my-jar.jar"
  timeToLiveSeconds: 360

  restartPolicy:
    type: Never
  volumes:      
    - hostPath: 
        type: FileOrCreate
        path: /Users/osamaanwer/code/config.yaml
      name: config-yaml
    - hostPath:
        type: FileOrCreate
        path: /Users/osamaanwer/code/my-jar.jar
      name: my-jar
         
  driver:
    cores: 1
    coreLimit: "1"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - mountPath: "/home/hadoop/config.yaml"
        name: config-yaml
      - mountPath: "/home/hadoop/app/lib/my-jar.jar"
        name: my-jar
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - mountPath: "/home/hadoop/config.yaml"
        name: config-yaml
      - mountPath: "/home/hadoop/app/lib/my-jar.jar"
        name: my-jar
```
       

        
**Spark operator details:**
```
  NAME      	NAMESPACE     	REVISION	UPDATED                             	STATUS  	CHART               	APP VERSION        
my-release	spark-operator	1       	2021-03-01 18:34:33.630578 +0500 PKT	deployed	spark-operator-1.0.7	v1beta2-1.2.0-3.0.0

```
I installed with the following command (did installed with mutating webhook):
`helm install my-release spark-operator/spark-operator --namespace spark-operator --set enableWebhook=true`

Note:
I am able to mount with following way
```
sparkConf:
    "spark.kubernetes.driver.volumes.hostPath.aws.mount.path": "xyz" 
    "spark.kubernetes.driver.volumes.hostPath.aws.options.path": "xyz"
```
