### ISSUE TITLE
Configmap is not working with Spark

### ISSUE THREAD

**Issue by connectsachit** [kubeflow/spark-operator#1188]
Following config map example is given on the official git link. This is not working and it is not giving the configmap at the pod. 
Even the environment variable form of configmap is not working. Could you please look into this and help?

Thanks

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Never
  volumes:
    - name: config-vol
      configMap:
        name: dummy-cm
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm

**Comment by leandro-rouberte** [comment]
Hi, friend. I was having the same issue. I changed my spark-operator manifest to use the latest spark-operator image. And it did the trick for me. Hope this helps:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: spark
spec:
  releaseName: spark-operator
  chart:
    repository: "https://googlecloudplatform.github.io/spark-on-k8s-operator"
    version: "1.0.5"
    name: "spark-operator"
  values:
    image:
      tag: "latest"
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.5"
        memory: "512Mi"
    webhook:
      enable: true
```
