### ISSUE TITLE
automountServiceAccountToken

### ISSUE THREAD

**Issue by jinxingwang** [kubeflow/spark-operator#1189]
Anyone want me to support this automountServiceAccountToken feature into spark operator?

**Comment by hopper-signifyd** [comment]
@jinxingwang That would be great to have!

**Comment by sparsh-95** [comment]
Can any maintainer share the update on when this will be prioritized? TIA :)

**Comment by Aransh** [comment]
Any updates on this issue? we need this for compliance with Azure Government cloud.
@jinxingwang @sparsh-95 

CC @EliranTurgeman

**Comment by jacobsalway** [comment]
Could you go into a bit more detail on the specific compliance requirements? Is credential auto-mounting disabled in these clusters?

**Comment by Aransh** [comment]
@jacobsalway Sure
Azure Microsoft defender reported a High Severity security finding as below

"Kubernetes clusters should disable automounting API credentials" - Disable automounting API credentials to prevent a potentially compromised Pod resource to run API commands against Kubernetes clusters. For more information, see https://aka.ms/kubepolicydoc.

So in order to mitigate the above finding need to disable automounting of service account token by setting automountServiceAccountToken = false on all pods.
This is not possible with the chart currently, or with the operator in general (for generated spark app pods).

I will mention the idea of the policy is "while obviously some apps require serviceAccount tokens, it shouldn't be mounted *by default* to avoid misuse, and instead should only be manually (and explicitly) mounted as a volume when needed", example of manually mounting to a pod:
```
    volumes:
    - name: kube-api-access
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access
      readOnly: true
```

Anyway, this is a required policy for work with Azure Government cloud
