### ISSUE TITLE
Allow folder patterns for JARs into Java classpath 

### ISSUE THREAD

**Issue by Jimmy-Newtron** [kubeflow/spark-operator#1201]
It is not the first time that I encounter this problem

Suppose that you have the following
```
/opt
   |- spark/libs/*.jar
   |- customLibs/*.jar
```
You can add your **customLibs** while executing the _spark-submit_ via the --jars parameter 

```
spark-submit --master local[*] --jars /opt/customLibs/*.jar --mainClass MyApp application.jar
```
The syntax with globPattern work in CLI, but when using the spark-operator we cannot have the same behavior

```yaml
spec:
  deps:
    jars:
      - local:///opt/customLibs/*.jar 
```

### Details
In fact spark-operator builds the spark.property file with the following
```ini
"spark.jars": "local\:\/\/\/opt\/customLibs\/*.jar"
```

spark is able to parse the configuration of patterns only when it is relative to the file system like
```ini
"spark.jars": "\/opt\/customLibs\/*.jar"
```

### Attempted to bypass the problem
Instead of passing the jars with the expected yaml property I have tried to provide the following
```yaml
spec:
  sparkConf:
    "spark.jars": "/opt/customLibs/*.jar"
```
and as you can imagine the **spark.jars** key has been overridden by the spark-operator, removing my definition (no merge or concatenation)
