### ISSUE TITLE
configurable sized scratch/tmp space mounts for executors

### ISSUE THREAD

**Issue by jdonnelly-apixio** [kubeflow/spark-operator#1215]
I was hoping if someone could tell me if what I'd like to accomplish is possible and if so, point me in the right direction.

I would like to be able to mount unique ReadWriteOnce persistent volume claims to each executor in the given spark app yaml. We are using aws eks and we have some jobs that need to write a large amount to these scratch/tmp space directories and the executors will get evicted when they write too much on a worker node. I see that you can specify one single shared persistent volume claim in the user guide:
```
spec:
  volumes:
    - name: "spark-local-dir-1"
      persistentVolumeClaim:
        claimName: network-file-storage
  executor:
    volumeMounts:
      - name: "spark-local-dir-1"
        mountPath: "/tmp/dir1"
```
But I am worried using one shared persistent volume claim will hit a bottleneck for larger jobs. Is it possible to parameterize the persistent volume claim with some kind of executor id? (e.g. claimName: ebs-pv{N}, where executor 1 uses ebs-pv1, executor 2 uses ebs-pv2, etc.). We are using airflow currently to kick off spark jobs, so I was thinking I could write something to optionally create one persistent volume claim for each executor using [ebs-cni](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html). But that would only work if the spark operator supported specifying different claims for different executors.

I guess another approach that avoids having large disks mostly empty on worker nodes would be to have a separate worker node group that uses instances with larger disks, but this wouldn't be too flexible.

Alternatively, can anyone think of a better way to accomplish this?
