### ISSUE TITLE
spark executor pods not releasing memory when idle

### ISSUE THREAD

**Issue by luciferksh** [kubeflow/spark-operator#1218]
I am running spark structure streaming on k8s. when the job is idle the memory uses of the executor pods is not coming down.
is the running pod release memory or it reserves all the memory assign to it?

**Comment by luciferksh** [comment]
@liyinan926 Pls advice

**Comment by jdonnelly-apixio** [comment]
I haven't tried it yet, but you could try to use dynamic allocation. I'm not sure how it would handle spark streaming executors in this case though.

**Comment by jdonnelly-apixio** [comment]
We were able to use dynamic allocation for this and it works very well. It's pretty simple to use for an app:

```
spec:
  ...
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 5
```
