### ISSUE TITLE
Unable to pass environment variables in the example app on AKS/EKS 1.19. (works fine on 1.17)

### ISSUE THREAD

**Issue by Venkatesh89-Github** [kubeflow/spark-operator#1229]
I have installed the spark operator on AKS 1.19 but when I pass the environment variable in the given example 
      https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-py-pi.yaml

      it does not get passed to the pod definition. I have already enabled the web hook as well.
      
      Below is the pod manifest (spark.-.Copy.-.Copy.log) I want to create.
      
      
[spark - Copy - Copy.log](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/6325594/spark.-.Copy.-.Copy.log)

**Comment by JunaidChaudry** [comment]
Having the same issue on EKS

**Comment by JunaidChaudry** [comment]
@Venkatesh89-Github Can you Update the Title so that it covers both of us? I think it is a sparkOperator issue, rather than AKS/EKS specific?

**Comment by Venkatesh89-Github** [comment]
Can someone help on this issue please?

**Comment by swill** [comment]
I think I am running into the same issue.  In my case, I am using RKE2.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8+rke2r1", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-26T00:03:32Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8+rke2r1", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-26T00:03:32Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

This **works** for me:
```
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-s3-credentials
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: aws-s3-credentials
        key: AWS_SECRET_ACCESS_KEY
```

However, all of the following **do not work**:
```
    env:
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: aws-s3-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: aws-s3-credentials
            key: AWS_SECRET_ACCESS_KEY
```
and
```
    envFrom:
      - secretRef:
          name: aws-s3-credentials
```

The main concern I have is that `envSecretKeyRefs` is set to be deprecated, but the official Kubernetes methods for passing in the env vars does not seem to working as expected.

According to the [SparkPodSpec](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkpodspec), all of these options should work, but they don't...
