### ISSUE TITLE
enable-ui-service breaks helm chart

### ISSUE THREAD

**Issue by kehao95** [kubeflow/spark-operator#1274]
It seems that `enable-ui-service` was added recently.
 Which result in passing `-enable-ui-service=true/false` on `spark-operator` deployment even with old version `spark-operator` who doesn't accept this flag.

my case:
```yaml
# helm chart
  spark-operator:
    namespace: spark
    enabled: true
    chart: spark-operator/spark-operator
    version: 1.1.3
    valuesFile: values/spark-operator.yaml

# values.yaml

image:
  # -- Image repository
  repository: gcr.io/spark-operator/spark-operator
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "v1beta2-1.2.0-3.0.0"
...
uiService:
  # -- Enable UI service creation for Spark application
  enable: true
```

Error:
```

 + echo root:x:0:0:root:/root:/bin/bash
 root:x:0:0:root:/root:/bin/bash
 + [[ -z root:x:0:0:root:/root:/bin/bash ]]
 + exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace=spark -enable-ui-service=true -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-resource-quota-enforcement=false
 flag provided but not defined: -enable-ui-service
 Usage of /usr/bin/spark-operator:
   -alsologtostderr
         log to standard error as well as files
   -controller-threads int
         Number of worker threads used by the SparkApplication controller. (default 10)
   -enable-batch-scheduler
         Enable batch schedulers for pods' scheduling, the available batch schedulers are: (volcano).
   -enable-metrics
         Whether to enable the metrics endpoint.
   -enable-resource-quota-enforcement
         Whether to enable ResourceQuota enforcement for SparkApplication resources. Requires the webhook to be enabled.
   -enable-webhook
         Whether to enable the mutating admission webhook for admitting and patching Spark pods.
   -ingress-url-format string
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: spark-operator
    meta.helm.sh/release-namespace: spark
  labels:
    app.kubernetes.io/instance: spark-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spark-operator
    app.kubernetes.io/version: v1beta2-1.2.3-3.1.1
    helm.sh/chart: spark-operator-1.1.3
  name: spark-operator
  namespace: spark
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: spark-operator
      app.kubernetes.io/name: spark-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: spark-operator
        app.kubernetes.io/name: spark-operator
    spec:
      containers:
      - args:
        - -v=2
        - -logtostderr
        - -namespace=spark
        - -enable-ui-service=true
        - -ingress-url-format=
        - -controller-threads=10
        - -resync-interval=30
        - -enable-batch-scheduler=false
        - -label-selector-filter=
        - -enable-metrics=true
        - -metrics-labels=app_type
        - -metrics-port=10254
        - -metrics-endpoint=/metrics
        - -metrics-prefix=
        - -enable-resource-quota-enforcement=false
        image: gcr.io/spark-operator/spark-operator:v1beta2-1.2.0-3.0.0
        imagePullPolicy: IfNotPresent
        name: spark-operator
        ports:
        - containerPort: 10254
          name: metrics
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: spark-operator
      serviceAccountName: spark-operator
      terminationGracePeriodSeconds: 30

```

**Comment by theofpa** [comment]
Removing the argument `-enable-ui-service` from the deployment, results to the same error message but this time for the argument `-label-selector-filter=`. After removing both, the older versions of spark-operator start properly.

**Comment by sshah90** [comment]
Not sure but I see helm chart release had operator changes which break deployment for HelmChart Version >= 1.1.1

[HelmChart Release Compare](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/compare/spark-operator-chart-1.1.0...spark-operator-chart-1.1.1)

**Comment by vikidev** [comment]
> Removing the argument `-enable-ui-service` from the deployment, results to the same error message but this time for the argument `-label-selector-filter=`. After removing both, the older versions of spark-operator start properly.

@theofpa How do you remove these arguments?

**Comment by port3000** [comment]
> Removing the argument `-enable-ui-service` from the deployment, results to the same error message but this time for the argument `-label-selector-filter=`. After removing both, the older versions of spark-operator start properly.

@theofpa How did you remove these arguments?

**Comment by xpaulnim** [comment]
@port3000 see my cooment in #1157

**Comment by theofpa** [comment]
> > Removing the argument `-enable-ui-service` from the deployment, results to the same error message but this time for the argument `-label-selector-filter=`. After removing both, the older versions of spark-operator start properly.
> 
> @theofpa How did you remove these arguments?

In the container spec of the spark-operator deployment, I just removed the lines:

```
        - -enable-ui-service=true
        - -label-selector-filter=
```
so it now looks like this:
```
spec:
      containers:
      - args:
        - -v=2
        - -logtostderr
        - -namespace=
        - -ingress-url-format=
        - -controller-threads=10
        - -resync-interval=30
        - -enable-batch-scheduler=false
        - -enable-metrics=true
        - -metrics-labels=app_type
        - -metrics-port=10254
        - -metrics-endpoint=/metrics
        - -metrics-prefix=
        - -enable-resource-quota-enforcement=false
        image: gcr.io/spark-operator/spark-operator:v1beta2-1.1.2-2.4.5
...
```
