### ISSUE TITLE
Spark Driver Metrics missing

### ISSUE THREAD

**Issue by arghya18** [kubeflow/spark-operator#1282]
I am using the below to export driver and executor metrics but seems many important driver metrics are missing, please suggest what I am missing. I am using PySpark 3.1.1 and Below is my config

`  
monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
`

I am using the configuration from [https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/spark-docker/conf](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/spark-docker/conf)

Seems all the executor and many of the driver metrics are there but below driver metrics are missing
`
spark_driver_jvm_total_max_type_gauges
spark_driver_jvm_total_used_type_gauges
spark_driver_dagscheduler_job_alljobs_type_gauges
spark_driver_dagscheduler_job_activejobs_type_gauges
spark_driver_dagscheduler_stage_runningstages_type_gauges
spark_driver_dagscheduler_stage_waitingstages_type_gauges
spark_driver_dagscheduler_stage_failedstages
spark_driver_blockmanager_disk_diskspaceused_mb_type_gauges
spark_driver_blockmanager_memory_maxoffheapmem_mb_type_gauges
spark_driver_blockmanager_memory_maxonheapmem_mb_type_gauges`

I even tried checking curl localhost:8090 on driver pod but the above are missing there
Please suggest how to add those?

**Comment by jdonnelly-apixio** [comment]
@arghya18 For the jvm metric ones, you can find them without the spark_driver prefix and type_gauges postfix. They should be tagged with stuff like kubernetes_pod_name so that you can filter for just the driver pod. For the others... I haven't checked the default prometheus config for a while, but when it wasn't working for me a while back, I had to make some changes to the config. We run our spark apps with the monitoring section below. It also has links to spark source where you can poke around to find what you want.

```
monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.13.0.jar"
      port: 8090
      configuration: |
        ---
        lowercaseOutputName: true
        attrNameSnakeCase: true
        rules:
          # Driver DAGScheduler Metrics
          # These come from the application driver - https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/scheduler/DAGSchedulerSource.scala
          # Emulate timers for DAGScheduler like messagePRocessingTime
          - pattern: metrics<name=(\S+)\.(\S+)\.driver\.DAGScheduler\.(.*)><>Count
            name: spark_driver_DAGScheduler_$3_count
            type: COUNTER
            labels:
              app_namespace: "$1"
              app_id: "$2"
          #                    $1            $2                           $3       $4
          # e.g. metrics<name=default.spark-test-v40.driver.DAGScheduler.stage.failedStages, type=gauges><>Value
          # spark_driver_dagscheduler_stage_failedstages_type_gauges{app_id="spark-test-v40",app_namespace="default",} 0.0
          # - pattern: metrics<name=(\S+)\.(\S+)\.driver\.DAGScheduler\.(stage|job)\.(.*)><>Value
          - pattern: metrics<name=(\S+)\.(\S+)\.driver\.DAGScheduler\.(stage|job)\.(.*),.*><>Value
            name: spark_driver_DAGScheduler_$3_$4_gauge
            type: GAUGE
            labels:
              app_namespace: "$1"
              app_id: "$2"
          # Driver AppStatus Metrics
          # These come from the application driver (i think) - https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/status/AppStatusSource.scala
          # This doesn't work right now, but would really like to get it working at some point.
          - pattern: metrics<name=(\S+)\.(\S+)\.driver\.(appStatus|AppStatus|app status|app_status|appstatus)(.*)><>Count
            name: spark_driver_$3_$4_count
            type: COUNTER
            labels:
              app_namespace: "$1"
              app_id: "$2"
          - pattern: metrics<name=(\S+)\.(\S+)\.driver\.(appStatus|AppStatus|app status|app_status|appstatus)\.(stages|jobs|tasks)\.(.*)><>Value
            name: spark_driver_$3_$4_$5
            type: GAUGE
            labels:
              app_namespace: "$1"
              app_id: "$2"
          # Emulate histograms for CodeGenerator
          - pattern: metrics<name=(\S+)\.(\S+)\.driver\.CodeGenerator\.(.*)><>Count
            name: spark_driver_CodeGenerator_$3_count
            type: COUNTER
            labels:
              app_namespace: "$1"
              app_id: "$2"
          # Executors counters
          - pattern: metrics<name=(\S+)\.(\S+)\.(.*)\.executor\.(.*)><>Count
            name: spark_executor_$4_count
            type: COUNTER
            labels:
              app_namespace: "$1"
              app_id: "$2"
              executor_id: "$3"
          # Executors gauges
          # metrics<name=default.spark-test-v34.1.executor.threadpool.startedTasks, type=gauges><>Value
          #                 $1       $2         $3                  $4 
          # metrics<name=default.spark-test-v34.1.executor.threadpool.startedTasks, type=gauges><>Value
          - pattern: metrics<name=(\S+)\.(\S+)\.(.*)\.executor\.(.*)><>Value
            name: spark_executor_$4
            type: GAUGE
            labels:
              app_namespace: "$1"
              app_id: "$2"
              executor_id: "$3"
```
