### ISSUE TITLE
Example / Reference for customising spark-py docker image

### ISSUE THREAD

**Issue by brshravan-tech** [kubeflow/spark-operator#1302]
Hi Team,

Here is my use case.

We have an application which is built based on python-slim docker image. This creates virtual environment and installs the required python libraries into it and packages it as a docker image. Something like below

```
FROM python:3.7-slim AS compile-image
RUN apt-get update
<COPY Some files>
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN python3 -m ensurepip
RUN pip3 install --upgrade pip
# Install the required python packages
RUN pip3 install -r requirements.txt <--- installs bunch of python libraries
RUN python3 setup.py install <--- install our application code into python venv

ENV PATH="/opt/venv/bin:$PATH"
ENTRYPOINT [ "/opt/venv/bin/python" ]
CMD [ "/files/main.py" ]
```

Now, I want to convert it to spark application. For this, I think I need to customise spark-py docker image and above code to it. But I am unable to find any reference for doing it. Any pointers for doing this would be helpful

Thanks in advance

**Comment by jdonnelly-apixio** [comment]
To get that working, I didn't install job specific dependencies in the pyspark docker container, instead I packaged my python app and its dependencies in a zip file (note: any non-python data files won't be useable this way, e.g. botocore models used to generate api reqs). I put the built zip in s3 and reference it in my spark app yaml.

This is my hacky build script:
```
set -e

# sorry, its ugly
cd /workspace/apx-devops/spark_hive_metastore_schema_manager

version=$(cat VERSION.txt)

rm -fR spark_dist/*
rm -f dist/spark_hive_metastore_schema_manage*
pip wheel -r requirements.txt -w dist
python setup.py bdist_wheel
cp dist/* spark_dist/
for f in spark_dist/*.whl; do mv -- "$f" "${f%.whl}.zip"; done
cd spark_dist
for f in *.zip; do unzip $f; done
rm -f *zip
zip -r "spark-hive-metastore-schema-manager-${version}.zip" *
rm -f "../built_zips/spark-hive-metastore-schema-manager-${version}.zip"
cp "spark-hive-metastore-schema-manager-${version}.zip" ../built_zips/
s3cmd put --force "spark-hive-metastore-schema-manager-${version}.zip" s3://my_stg_bucket/pyspark/devops/spark_hive_metastore_schema_manager/
s3cmd cp --force "s3://my_stg_bucket/pyspark/devops/spark_hive_metastore_schema_manager/spark-hive-metastore-schema-manager-${version}.zip" s3://my_prd_bucket/pyspark/devops/spark_hive_metastore_schema_manager/
```

My driver.py
```
import sys
import importlib

if len(sys.argv) == 1:
    raise SyntaxError("Please provide a module to load.")
module = importlib.import_module(sys.argv[1])
sys.exit(module.main(sys.argv[2:]))
```

spark app yaml
```
spec:
  type: Python
  pythonVersion: "3"
  ...
  mainApplicationFile: "local:///opt/spark/work-dir/spark_hive_metastore_schema_manager/driver.py"
  ...
  deps:
    ...
    pyFiles:
    - "s3a://my_stg_bucket/pyspark/devops/spark_hive_metastore_schema_manager/spark-hive-metastore-schema-manager-0.1.3.zip"
```

I would definitely be interested in a more elegant solution though...

**Comment by brshravan-tech** [comment]
Thanks a lot "jdonnelly-apixio" for the reply.

I won't be able to put it in s3. So, I was thinking if I can package it within spark-py docker image so that driver can find it. Also, can you let me know, how you added "driver.py" to the spark-py image? I am assuming that you have created Dockerfile which takes spark-py as docker image and added your driver.py file to it. If so, can you tell me how this Dockerfile would look like? If possible, will you be able to share it?

Thanks

**Comment by jdonnelly-apixio** [comment]
The driver.py is a part of the python package I built. The spark operator extracts the python package to the spark working dir so that it can be used.

```
spec:
  ...
  deps:
    ...
    pyFiles:
    - "s3a://my_stg_bucket/pyspark/devops/spark_hive_metastore_schema_manager/spark-hive-metastore-schema-manager-0.1.3.zip"
```

I don't think you'd be able to extract the zip in the base docker image to the spark working dir without breaking the app. You could probably extract it to somewhere like `/opt/your_extracted_zip/` then create a sym link to it from the spark working dir in a docker init container for your driver and executors. So for the dockerfile, you could do:
```
ADD your_zip.zip /opt/
```

Then the spark app yaml could be something like:
```
spec:
  ...
  volumes:
    - name: driver-init-helper
      emptyDir: {}
  driver:
    volumeMounts:
      - name: driver-init-helper
        mountPath: /opt/spark/work-dir
    initContainers:
    - name: "driver-init-container"
      image: "your_container_repo/xxx-spark-app:v1.1.3"
      command:
      - "ln"
      - "-s" 
      - "/opt/your_zip_dir/"
      - "/mnt/driver_init/your_zip_name/"
      volumeMounts:
        - name: driver-init-helper
          mountPath: /mnt/driver_init
    executor:
       # do the same as the driver
```
