### ISSUE TITLE
.spec.deps.files  option invalid  in my application

### ISSUE THREAD

**Issue by joanjiao2016** [kubeflow/spark-operator#1312]
I use the ` .spec.deps.files `  option in my application , I found that .spec.deps.files  option could't work ：

1.  if  I use container-local mode as follows，the application could be submitted, but the file could't be identifed by the application and the application fanally failed：
```
deps:
    files:
      - "local:///opt/spark/props/sql.properties"
```
      
2. If I load the file in hdfs, my yaml is as follows， the applcation submitted with error：
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: tph
  namespace: sparkop
spec:
  type: Scala
  mode: cluster
  image: "repoIP/sparkop/rod:1.0"
  imagePullPolicy: IfNotPresent
  mainClass: tp
  mainApplicationFile: "local:///opt/spark/jars/tp.jar"
  sparkVersion: "3.1.1"
  sparkConf:
    "spark.kubernetes.kerberos.krb5.configMapName" : "krb5-config"
    "spark.kubernetes.hadoop.configMapName" : "hadoop-config"
  kerberos:
    enabled: true
    kerberosPrincipal: "tdhclient"
    keytabSecret: "tdhclient-keytab"
    keytabName: "tdhclient.keytab"
  deps:
    files:
      - "hdfs://namenodeIP:8020/user/tdhclient/sql.properties"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "2048m"
    labels:
      version: 3.1.1
    serviceAccount: sparkop
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    coreLimit: "1200m"
    instances: 2
    memory: "2048m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

![event截图](https://user-images.githubusercontent.com/42462099/127090837-be1f1006-35f6-4aed-bce8-6ce6defc2644.PNG)

Can any one help , thanks a lot !
