### ISSUE TITLE
securityContext not applying to SparkApplications

### ISSUE THREAD

**Issue by jstff** [kubeflow/spark-operator#1335]
Hello.

We are having an issue applying security contexts to our SparkApplications. The Spark Operator is running and the Admission Webhook has also ran and completed. Additionally, we are defining the security context in the SparkApplication's spec under `driver` and `executor` as outlined in the documentation.

Despite defining the security context, our SparkApplication jobs are failing with the following error.
`kubectl get pods -n bdp`
```
spark-sparkoperator-758d6b7f9f-c8rqv        1/1     Running                      0          26m
spark-sparkoperator-crd-cleanup-kbkpw       0/2     Completed                    0          46h
spark-sparkoperator-webhook-cleanup-92gs2   0/1     Completed                    0          46h
spark-sparkoperator-webhook-init-nzqbr      0/1     Completed                    0          21h
test-1-driver                               0/1     CreateContainerConfigError   0          25m
```
`kubectl describe pod test-1-driver -n bdp`
```
Warning  Failed       35s (x8 over 103s)  kubelet, ip-10-98-246-36.ec2.internal  Error: container has runAsNonRoot and image will run as root
```

This is our test SparkApplication yaml.
```yaml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test-1
  namespace: bdp
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark-on-caas-poc.artifactory.REDACTED.com/spark/base/pyspark:v2.4.5
  imagePullPolicy: Always
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  driver:
    podSecurityContext:
      runAsUser: 1000
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 2000
    cores: 1
    coreLimit: "1"
    memory: "512m"
    serviceAccount: spark-sparkoperator
    labels:
      version: 2.4.5
    env:
    - name: HTTP2_DISABLE # https://github.com/fabric8io/kubernetes-client/issues/2212#issuecomment-628551315
      value: "true"
  executor:
    podSecurityContext:
      runAsUser: 1000
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 2000
    coreLimit: "1"
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.5
    env:
    - name: HTTP2_DISABLE # https://github.com/fabric8io/kubernetes-client/issues/2212#issuecomment-628551315
      value: "true"
```

We are trying to ensure that all Spark related jobs are running as non-root, but we are not seeing the expected behavior based on the documentation. Any help that you can provide is much appreciated. Thank you!
