### ISSUE TITLE
batch scheduler not work

### ISSUE THREAD

**Issue by biaochen** [kubeflow/spark-operator#1343]
1. I'm using spark-operator(v1beta2-1.2.3-3.1.1) with volcano (v1.3.0), and spark-operator is installed with batchScheduler enabled. When applying following sparkapp to a machine with 16 cpus, I expect all 3 pods (1 driver, 2 executors) are pending, but in fact 1 driver and 1 executor starts running, 1 executor stays pending, which means gang-scheduling doesnot work. 
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: demo
  namespace: spark-operator
spec:
  batchScheduler: "volcano"
  batchSchedulerOptions:
    queue: dev
    priorityClassName: low
    resources:
      cpu: 18
  type: Python
  pythonVersion: "3"
  mode: cluster
  sparkVersion: "2.4.8"
  restartPolicy:
    type: Never
  driver:
    cores: 6
    coreRequest: "6"
    memory: "5g"
    labels:
      version: 2.4.8
    serviceAccount: spark
  executor:
    instances: 2
    cores: 6
    coreRequest: "6"
    memory: "5g"
    labels:
      version: 2.4.8
```
I've checked volcano schedulers' log, the reason seems to be that as minMember=1, when driver pod is created, it starts to allocate and can pass volcano's resource check and then start running. Then it starts to create executors...

2. Another issue relates to memory request. In the above yaml, I set memory to 5g, but the created pod doesnot have spec.containers.resources.requests.memory to be '5Gi'.

Thanks~
