### ISSUE TITLE
MountVolume.SetUp failed for volume

### ISSUE THREAD

**Issue by 1090ym** [kubeflow/spark-operator#1353]
How to resolve the problem? I can't volume mount the pvc of NFS. But the `graph-data-nfs-pvc` is normal. This is a bug?
---
log:
```
MountVolume.SetUp failed for volume "spark-conf-volume" : configmap not foun
```
---
yaml:
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-graph
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: '192.168.4.55:5000/graph:20210827212800'
  imagePullPolicy: IfNotPresent
  mainClass: cn.graph.TestApp
  mainApplicationFile: 'local:///opt/graph.jar'
  sparkVersion: 3.0.1
  terminationGracePeriodSeconds: 5
  sparkConf:
    spark.rpc.message.maxSize: '1024'
    spark.driver.memoryOverhead: 2G
    spark.driver.maxResultSize: 8G
  sparkUIOptions:
    servicePort: 4049
  restartPolicy:
    type: Never
  volumes:
    - name: "graph-data"
      persistentVolumeClaim:
        claimName: "graph-data-nfs-pvc"
  driver:
    cores: 1
    memory: 10G
    labels:
      version: 3.0.1
    serviceAccount: spark
    volumeMounts:
      - name: "graph-data"
        mountPath: "/opt/graph_data"
  executor:
    cores: 1
    instances: 8
    memory: 10G
    labels:
      version: 3.0.1
    volumeMounts:
      - name: "graph-data"
        mountPath: "/opt/graph_data"
```
