### ISSUE TITLE
Sparkapplications not submitted with helm upgrade

### ISSUE THREAD

**Issue by FloraZhang** [kubeflow/spark-operator#1355]
Hi experts,

I'm using helm to manage the install and upgrade for sparkapps. With latest sparkoperator I noticed that sparkapplications are not submitted to the operator when doing helm upgrade. Below are steps to recreate my issue:
1) In my templates folder I have `spark-pi.yaml` that runs infinitely and I have a `sparkapp-cleanup-job.yaml` that responsible for cleanup sparkapplication with a pre-upgrade hook:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: sparkapp-cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade, post-delete
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
  labels:
    app.kubernetes.io/name: {{ include "sparkapp.name" . }}
    helm.sh/chart: {{ include "sparkapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      name: sparkapp-cleanup-job
    spec:
      serviceAccountName: sparkapp-admin
      restartPolicy: OnFailure
      containers:
      - name: delete-sparkapp
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
         - "/bin/sh"
         - "-c"
         - |
           curl -ik \
           -X DELETE \
           -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
           -H "Accept: application/json" \
           -H "Content-Type: application/json" \
           https://kubernetes.default.svc/apis/sparkoperator.k8s.io/v1beta2/namespaces/{{ .Release.Namespace }}/sparkapplications/spark-pi
```
2) I deploy this sparkapplication with `helm3 upgrade spark-pi --install .  --namespace default`
3) Once it's submitted to the spark-operator and running, I deploy it again to mimic an upgrade: `helm3 upgrade spark-pi --install .  --namespace default`
4) I noticed that after the cleanup-job running the old spark-pi pod is terminated. But the new pod is not coming up.
5) I checked sparkapplications with `kubectl get sparkapplications.sparkoperator.k8s.io` and see that its status is blank forever:
```
NAME                       STATUS    ATTEMPTS   START                  FINISH       AGE
spark-pi                                                                          11m
```
6) If I delete the spark-operator pod this sparkapplication will be submitted. I'm now using this as a workaround for the issue.

Thanks,
Flora
