### ISSUE TITLE
Driver ignores extraJavaOptions

### ISSUE THREAD

**Issue by Charmelionag** [kubeflow/spark-operator#1356]
Hello,
My SparkApplication yaml file has the extraJavaOptions set for both driver and executor, like that `spec.[driver|executor].javaOptions`
Nevertheless, driver will ignore this parameter and not create `--conf` containing my javaOptions.
Here's my SparkApplication file
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: reset-shop-ca-pp
spec:
  arguments:
  - "-env"
  - "/cm/environment.conf"
  - "-conf"
  - "/cm/reset-shop.conf"
  - "-name"
  - "preprod_************-reset-shop"
  - "-group"
  - "bidonesco"
  imagePullSecrets:
  - regcred
  sparkConf:
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.endpoint: "s3.eu-west-3.amazonaws.com"
  type: Scala
  mode: cluster
  image: "**********/spark3.1.1-s3:0.0.1"
  imagePullPolicy: Always
  mainClass: com.********.reset.Launcher
  mainApplicationFile: "s3a://**********************/reset-shop-3.0.0-SNAPSHOT-jar-with-dependencies.jar"
  sparkVersion: "3.1.2"
  restartPolicy:
    type: Never
  driver:
    javaOptions: "-Dlog4j.configuration=log4j.properties -Denvironment.conf.path=environment.conf  -Dapplication.conf.path=reset-shop.conf"
    deps:
      files:
      - "/cm/log4j.properties"
      - "/cm/environment.conf"
      - "/cm/reset-shop.conf"
    configMaps:
    - name: resest-shop-ca-pp
      path: /cm
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-creds
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: aws-creds
        key: AWS_SECRET_ACCESS_KEY
    cores: 1
    memory: "4G"
    labels:
      version: 3.1.2
    serviceAccount: spark-operator-spark
  executor:
    javaOptions: "-Dlog4j.configuration=log4j.properties -Denvironment.conf.path=environment.conf  -Dapplication.conf.path=reset-shop.conf"
    deps:
      files:
      - "/cm/log4j.properties"
      - "/cm/environment.conf"
      - "/cm/reset-shop.conf"
    configMaps:
    - name: resest-shop-ca-pp
      path: /cm
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: aws-creds
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: aws-creds
        key: AWS_SECRET_ACCESS_KEY
    cores: 5
    instances: 4
    memory: "12G"
    labels:
      version: 3.1.2
```

Here's the spark submit inside the driver
```
/opt/spark/bin/spark-submit --conf spark.driver.bindAddress=172.30.26.229 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class com.*******.reset.Launcher s3a://*****************/reset-shop-3.0.0-SNAPSHOT-jar-with-dependencies.jar -env /cm/environment.conf -conf /cm/reset-shop.conf -name preprod_***********-reset-shop -group bidonesco
```
As you can see we have no `--conf extraJavaOptions` mentioned and eventually I get an error.

Has anyone encountered this type of error before?
Thank you
