### ISSUE TITLE
path in hostPath for Volumes does not work with symlink

### ISSUE THREAD

**Issue by Taqas** [kubeflow/spark-operator#1382]
I've tried using a symlink as path in hostPath for a Volume, but the Spark app cannot find the mounted path this way.

Suppose there is a symlink from `Users/<user>/data` to `/data` using `/etc/synthetic.conf`. The following setup does not work 
```yaml
volumes:
  - name: data-to-mount
    hostPath:
      path: /data
mounts:
  data-to-mount: /mnt/data
```

A direct reference to the directory does work
```yaml
volumes:
  - name: data-to-mount
    hostPath:
      path: /Users/<user>/data
mounts:
  data-to-mount: /mnt/data
```
