### ISSUE TITLE
[Chart] Webhook init and cleanup template files have wrong toleration block placement

### ISSUE THREAD

**Issue by HeshamMeneisi** [kubeflow/spark-operator#1393]
Tolerations are placed outside the if block.

This is in both [webhook-cleanup-job.yaml](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/6939cbd887adda19984ed5f75fd49dcbfc7c09b4/charts/spark-operator-chart/templates/webhook-cleanup-job.yaml#L49) and [webhook-init-job.yaml](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/6939cbd887adda19984ed5f75fd49dcbfc7c09b4/charts/spark-operator-chart/templates/webhook-init-job.yaml#L39)

When webhooks are disabled, the file will only contain tolerations which causes this error from `helm-operator`:
```error
Warning  FailedReleaseSync  104s (x6 over 10m)  helm-operator  synchronization of release 'spark-operator' in namespace 'spark-operator' failed: installation failed: unable to build kubernetes objects from release manifest: error validating "": error validating data: [apiVersion not set, kind not set]
```

**Comment by ericvenarusso** [comment]
I had the same problem using nodeSelector. As it is outside the block, the template is generated incorrectly by helm.

```yaml
nodeSelector:
        app: example
---
# Source: spark-operator/templates/webhook-cleanup-job.yaml
nodeSelector:
        app: example
---
# Source: spark-operator/templates/webhook-init-job.yaml
nodeSelector:
        app: example
---
```
