### ISSUE TITLE
How to handle errors in spark code so that spark operator treats it as a failure when restartPolicy is set to OnFailure

### ISSUE THREAD

**Issue by gauravbh1** [kubeflow/spark-operator#1402]
I have a spark structured streaming application which I am running using the sparkoperator
Here is the restartPolicy that I have specified.
```
  restartPolicy:
    type: OnFailure
    onFailureRetries: 20
    onFailureRetryInterval: 11
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
```
My application fails sometimes for some reasons (like unable to connect to kafka broker etc). In my application, I am throwing an exception from the main method in such erroneous cases. I was expecting  the driver pod to restart itself in such cases. However with the given policy, the driver pod goes into COMPLETED state. Any idea how to handle the code so that when an exception is thrown, spark operator treats it as a failure and restarts the driver pod? I cannot use the restart policy Always.
