### ISSUE TITLE
Adding exposed ports on driver spec fails

### ISSUE THREAD

**Issue by lboudard** [kubeflow/spark-operator#1404]
I'm trying to set some additional ports (trying to get a jupyter notebook as driver) as defined [in driver specs](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkoperator.k8s.io/v1beta2.DriverSpec).

Applying the manifest fails with the following error:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(SparkApplication.spec.driver): unknown field "ports" in io.k8s.sparkoperator.v1beta2.SparkApplication.spec.driver
```

Below my application definition:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-job
spec:
  type: Python
  pythonVersion: "3"
  mode: client
  image: ###
  imagePullPolicy: Always
  mainApplicationFile: local:///home/user/myapp/__main__.py
  sparkVersion: "3.2.0"
  sparkConfigMap: spark-conf
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
  driver:
    ports:
    - name: jupyter-lab
      containerPort: 8080
      protocol: TCP
    - name: gateway
      containerPort: 8888
      protocol: TCP
    serviceAccount: spark
    cores: 2
    memory:  "512m"
    envFrom:
      - configMapRef:
          name: myapp
      - secretRef:
          name: myapp
    secrets:
      - name: spark
        path: /mnt/secrets
        secretType: GCPServiceAccount
  executor:
    serviceAccount: spark
    cores: 2
    memory: "512m"
    envFrom:
      - configMapRef:
          name: myapp
      - secretRef:
          name: myapp
    secrets:
      - name: spark
        path: /mnt/secrets
        secretType: GCPServiceAccount
```

I tried to customize the other fields defined in driver spec and it seems working.

Version info:
chart-info: `spark-operator-1.1.10`
spark-operator version: `v1beta2-1.2.3-3.1.1`
