### ISSUE TITLE
PVC storageClass & sizeLimit aren't exposed when deploying spark executors with dedicated PVCs

### ISSUE THREAD

**Issue by orsagiv94** [kubeflow/spark-operator#1461]
In order to deploy PVC with every spark executor, it is needed to use multiple configurations mentioned in spark documentation -

From spark documentation, these are the needed configurations to use when setting a volume as local storage -
 
```
spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.claimName=OnDemand
spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass=gp
spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit=500Gi
spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path=/data
spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly=false
```

currently, spark operator only allows the following -
```
spec:
  volumes:
    - name: "spark-local-dir-1"
      persistentVolumeClaim:
        claimName: network-file-storage
  executor:
    volumeMounts:
      - name: "spark-local-dir-1"
        mountPath: "/tmp/dir1"
```

And there is no way to pass the further ones(storageClass, sizeLimit, readOnly)

My own solution was to add these missing values directly on the spark session in my application’s code

**Comment by Nagarajj** [comment]
@orsagiv94 were you able to mount pvc on the executor with above configurations (especially onDemand claim) using sparkOperator, we get "unable to create directory under the mount path /data" error. 

we see the pvc has been mounted onto the executor and SPARK_LOCAL_DIRS points to it. Did you have to make any other changes ? (for ex: any changes in the spark image you use, such as the UID of the image ?)

Thanks in advance.

**Comment by orsagiv94** [comment]
Hey @Nagarajj,
actually, we didn't mount it to "/data" path as described in spark docs.
instead, we used the second code example where the mount path is "/tmp/dir1"

and the only further configurations that we had to manually push to spark session options were - 
* sizeLimit
* storageClass
* readOnly

**Comment by itamar-otonomo** [comment]
> @orsagiv94 were you able to mount pvc on the executor with above configurations (especially onDemand claim) using sparkOperator, we get "unable to create directory under the mount path /data" error.
> 
> we see the pvc has been mounted onto the executor and SPARK_LOCAL_DIRS points to it. Did you have to make any other changes ? (for ex: any changes in the spark image you use, such as the UID in the image ?)
> 
> Thanks in advance.

Hi, I'm suffering from the same issue. On AWS, trying to get the SPARK_EXECUTOR_DIRS to point to an OnDemand PVCs dynamically created (as described [here](https://docs.datamechanics.co/docs/mounting-volumes#dynamically-provision-volumes-using-persistent-volume-claims)). The issue is that the executor pod is running on UID 185 and GID 0 but the mounted PVC is owned by root, without write permissions for a user with gid 0.
See that the authors do try to go around the issue by adding the creation of the mount directory and chmodding/chowning it to 185:0 which is the user ID of the spark executor process. Nevertheless, when running the actual spark job I see that the PVC is mounted as root:root (which is the source of the error - the internal directory for the spill data cannot be created due to uid 185 has no permission there).
In an attempt to go around that and tried to pass a securityContext to the executors and force the FsGroup=185 and I see that securityContext was not applied in the pod even though it was requested in the sparkApp.

Reading around, I did not find much in the subject. Only a few reports that people switched back to running their spark jobs as user root, which "solves" the issue.
Please let us know if you get around this issue.

**Comment by dskatz** [comment]
Hi, We have also been having an issue implementing dynamic PVC per executor on k8s.  The documentation [here](https://docs.datamechanics.co/docs/mounting-volumes#dynamically-provision-volumes-using-persistent-volume-claims) is good, however as @itamar-otonomo points out there are issues with the chown/chmod commands.

Adding a `podSecurityContext` to the executor will remedy this issue on mount. e.g.
```
  executor:
    podSecurityContext:
      fsGroup: 185
      fsGroupChangePolicy: "OnRootMismatch"
```

This has been tested on K8s 1.20.  `fsGroupChangePolicy` is not available prior to k8s 1.20

Full spec for reference:
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: pyspark-pi-test
  namespace: default
spec:
  driver:
    coreLimit: 1200m
    cores: 1
    labels:
      version: 3.1.1
    memory: 512m
    serviceAccount: spark
  executor:
    podSecurityContext:
      fsGroup: 185
      fsGroupChangePolicy: "OnRootMismatch"
    cores: 1
    instances: 1
    memory: 512m
    envVars:
      SPARK_EXECUTOR_DIRS: /tmp/data
  image: gcr.io/spark-operator/spark-py:v3.1.1
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  mode: cluster
  pythonVersion: "3"
  sparkConf:
     spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.claimName: "OnDemand"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.storageClass: "gp2"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.data.options.sizeLimit: "500Gi"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.path: "/tmp/data"
     spark.kubernetes.executor.volumes.persistentVolumeClaim.data.mount.readOnly: "false"
  restartPolicy:
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
    type: OnFailure
  sparkVersion: 3.1.1
  type: Python
```
