### ISSUE TITLE
No Filesystem for scheme 'abfss' with spark-on-k8s Operator

### ISSUE THREAD

**Issue by murilommen** [kubeflow/spark-operator#1472]
Hey guys!

I am trying to run a very simple spark job that will Extract some data from my Azure Data Lake and print it on screen. 
For that I have built an image using a Dockerfile that looks like this:

```Dockerfile
FROM gcr.io/spark-operator/spark-py:v3.1.1

USER root:root

RUN mkdir -p /app
WORKDIR /app

COPY jars/ /opt/spark/jars
COPY simple-etl-job.py /app
WORKDIR /app

USER 1001
```

And when I launch it as a job on Kubernetes it returns me an error saying:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o56.load.
: java.io.IOException: No FileSystem for scheme: abfss
```

The strange thing is, I am copying to the `/opt/spark/jars` directory the same jars used for a local `spark-submit` job that does the same as my K8s code and runs successfully. 
Those jars are:
- hadoop-azure-3.2.0.jar          
- wildfly-openssl-1.0.4.Final.jar
- hadoop-azure-datalake-3.2.0.jar

One other thing that I've already tried was to set the jars with the `--jars` flag, as stated [in the docs](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/74ea1c86c9a595e6c1c8a0c2c40a50bf89288ede/docs/user-guide.md#specifying-application-dependencies), and the logs identify that I am adding those same specific Jars, but same error appears.

What else could I possibly be doing wrong? 

P.S.: Here is my spark CRD:

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: simple-spark-etl-job
  namespace: spark-operator
spec:
  type: Python
  mode: cluster
  image: "<my-org>/<my-image>:<my-tag>"
  imagePullPolicy: Always
  mainApplicationFile: "local:///app/simple-etl-job.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: default
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.1.1
```

I have also opened [this question](https://stackoverflow.com/questions/70926753/no-filesystem-for-scheme-abfss-with-spark-on-k8s-operator) on Stack Overflow, so it can get more visibility.
