### ISSUE TITLE
History server -SSL issue

### ISSUE THREAD

**Issue by Bhagi33** [kubeflow/spark-operator#1480]
```
Hi Team,
I deployed spark history server, i configured ssl for history server , but error is thrown in accessing the history server UI.
```
-----------------------------------------------------------------------------------
```
spark.properties:
    spark.authenticate: true
    spark.history.ui.acls.enable: false
    spark.ssl.enabled: true
    spark.ssl.key-password: xxxxxxx
    spark.ssl.keystore: /persistent/ssl_certs/spark-keystore.jks
    spark.ssl.truststore: /persistent/ssl_certs/spark-truststore.jks
    spark.ssl.keystore-password: /persistent/ssl_certs/keystore_password
    spark.ssl.truststore-password: /persistent/ssl_certs/truststore_password
    spark.ssl.historyServer: true
```
-----------------------------------------------------------------------------------------------
kubectl logs spark-history-server-59486df6b7-bjft4 -n spark-sample-test
![image](https://user-images.githubusercontent.com/68953135/153886993-2a968a35-a053-4398-a216-fcd8d3bdb119.png)
------------------------------------------------------------------
curl -kv https://0.0.0.0:18480/ -vvvv
* Rebuilt URL to: https://0.0.0.0:18480/
* Trying 0.0.0.0...
* TCP_NODELAY set
* Connected to 0.0.0.0 (127.0.0.1) port 18480 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
* CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS alert, Server hello (2):
* error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
can you please help me fixing this issue, i tried ssl with selfsigned and signed with CA. but observed same issue with both certs
