### ISSUE TITLE
Spark application Driver pods inheriting the labels from SparkScheduledApplication results issues with ArgoCD

### ISSUE THREAD

**Issue by brshravan-tech** [kubeflow/spark-operator#1484]
Hi Team,

We are using ArgoCD for managing the Kubernetes and other clusters in our organisation. 
I have installed spark-operator and created manifest file for registering SparkScheduledApplication which spawns a driver+executor pods for running spark application every 30 mins.

As part of managing the cluster, ArgoCD adds a label to "SparkScheduledApplication" manifest for tracking any changes. When the spark driver pod is getting created every 30 mins, this new pod also inheriting the argo label that was added to "SparkScheduledApplication". Because of this Argo starts monitoring this driver pod also. But as we don't have any preconfigured/preregistered manifest file for these driver pods, argoCD complains about out of sync and suggests to prune. 
This overall label inheriting by driver pods making the issues with ArgoCD in managing the cluster. Do we have any way to control this label inheritance from "SparkScheduledApplication" to Spark driver pod?

Thanks

**Comment by TomHellier** [comment]
I use argocd to deploy my spark applications and I dont see this issue.

 Do you have a copy of the scheduledsparkapplication resource you would be willing to share? I am wondering if you are adding the argocd label to your driver pod spec?

What version of argocd and spark-on-k8s-operator are you using

**Comment by brshravan-tech** [comment]
@TomHellier 

Thanks for the reply...

Below is the cut down version of scheduledsparkapplication resource yaml file

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: testname
  namespace: spark
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Allow
  timeToLiveSeconds: 900
  template:
    type: Python
    pythonVersion: "3"
    mode: cluster
    sparkVersion: "3.1.1"
    restartPolicy:
      type: OnFailure
      onFailureRetries: 1
      onFailureRetryInterval: 10
      onSubmissionFailureRetries: 2
      onSubmissionFailureRetryInterval: 10
    driver:
      coreRequest: "500m"
      memory: "512m"
      ephemeral-storage: "512m"
      labels:
        version: 3.1.1
      serviceAccount: spark
    executor:
      coreRequest: "500m"
      instances: 1
      memory: "512m"
      ephemeral-storage: "512m"
      labels:
        version: 3.1.1
```

I am using "v1beta2-1.2.3-3.1.1" version spark-operator and scheduledsparkapplication CRD are from "v1beta2-1.0.1-2.4.4"
