### ISSUE TITLE
javaOptions  and spark.driver.extraJavaOptions are ignored

### ISSUE THREAD

**Issue by yevsh** [kubeflow/spark-operator#1491]
operator 3.1.1

`javaOptions: "-DXXX=test"`

and

`
"spark.driver.extraJavaOptions" : "-DXXX=test"`

are ignored!

I don't see them in the log under /opt/spark/bin/spark-submit

and in my java code:

  ` System.out.println("XXX=" + System.getProperty("XXX"));`

I see:
XXX=null

can someone check?

**Comment by dcoliversun** [comment]
Please make sure that the spark entrypoint.sh in the spark operator image is the same as the spark entrypoint.sh at runtime

**Comment by yevsh** [comment]
What do you mean? 
entrypoint.sh that comes with the operator image should be same as entrypoint.sh that comes in the base image of the spark application which is Apache spark 3.1.1?

I believe they are different by definition

**Comment by dcoliversun** [comment]
No. The base image of spark-operator is spark, and you need to keep base image version with spark version which is needed for spark application. I suspect the cause of your problem is that the two versions are inconsistent resulting in different spark `entrypoint.sh`.

**Comment by yevsh** [comment]
operator image is:
spark-operator:v1beta2-1.3.3-3.1.1

The spark application image that I am submitting is 
```
FROM ...spark:v3.1.1.   (apache)
....
ENTRYPOINT [ "/opt/entrypoint.sh" ]
```

**Comment by yevsh** [comment]
I verified that entrypoint.sh are same

**Comment by yevsh** [comment]
@dcoliversun any ideas?

**Comment by dragan-vujovic** [comment]
I am facing the same issue when trying to set the basic authentication for spark-solr connector as explained [here](https://github.com/lucidworks/spark-solr):  
`--conf 'spark.driver.extraJavaOptions=-Dbasicauth=solr:SolrRocks'`. I've tried both spark.driver.extraJavaOptions and javaOptions in the driver section. I am using the `gcr.io/spark-operator/spark:v3.1.1-hadoop3` image.

**Comment by dragan-vujovic** [comment]
> I don't see them in the log under /opt/spark/bin/spark-submit  

>  `+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.254.35.172 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class xxxxxxxxxxx`  

Looks like these properties are passed through the properties-file `/opt/spark/conf/spark.properties`. I checked the contents in a running driver pod and all the properties are there. The problem for me was that I didn't set the executor java options. For spark-solr you need to set both driver and executor options. This solved the problem for me.

**Comment by yevsh** [comment]
@dragan-vujovic can you please elaborate how did you solve it? how are you sending the -D to executor?

**Comment by dragan-vujovic** [comment]
@yevsh Here's my full `yaml` file with some parts left out. Hope it helps.

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: application-name
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.1.1-hadoop3"
  imagePullPolicy: Always
  mainClass: package.className
  mainApplicationFile: "path/to/application.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  sparkConf:
    ...
    ...
    ...
    spark.driver.extraJavaOptions: "-Dbasicauth=username:password"
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
  hadoopConf:
    ...
    ...
    ...
  driver:
    javaOptions: "-Dbasicauth=username:password"
    cores: 1
    coreLimit: "1200m"
    memory: "32g"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    javaOptions: "-Dbasicauth=username:password"
    cores: 16
    instances: 20
    memory: "128G"
    labels:
      version: 3.1.1
```
