### ISSUE TITLE
Setup ingress support directly from Helm Chart

### ISSUE THREAD

**Issue by viktoriaas** [kubeflow/spark-operator#1526]
Hello, 
we set up `spark-on-k8s-operator` with UI enabled. We provide dynamic DNS and automatic `letsencrypt` certificates in our cluster so it is possible to create any url on HTTPS automatically just by setting a couple of annotations in `Ingress` + tls part.

We configured ingressURL to the specific pattern which includes namespace and application name. However, later we realized people who run `SparkApplication` tend to misconfigure `sparkUIOptions`, especially:
- ingress annotations required for generating a certificate
- `ingressTLS` part where they have to provide TLS host according to pattern configured in Operator which can be a rather long string (if the namespace is long).

On top of that, ingress configuration is not something directly connected to `SparkApplication` so we suggest possibility to set cluster-wide Ingress TLS support in Helm `values.yaml`. The modification requires the possibility to add custom annotations in values and a modification in code that detects if cluster-wide TLS support is desired. If yes, the host url in tls part of ingress can be set to the same url as in `rules[].host` because a certificate is going to be issued for that url (where app is served). 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-2-ui-ingress
  namespace: [namespace]
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod             <-- custom required annotation
    kubernetes.io/ingress.class: nginx                           <-- custom required annotation
    kubernetes.io/tls-acme: "true"                               <-- custom required annotation
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"  <-- custom required annotation
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    sparkoperator.k8s.io/app-name: spark-2
rules:
  - host: [host_url]
    http:
      paths:
      - backend:
          service:
            name: spark-2-ui-svc
            port:
              number: 4040
        path: /[namespace]/[app_name](/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - [host_url]
    secretName: [ingress_name]-tls
```
