### ISSUE TITLE
possible to set executor `resources.requests.memory` ?

### ISSUE THREAD

**Issue by dminca** [kubeflow/spark-operator#1548]
is there a way to set for executor.

```yml
resources:
  requests:
    memory: 512Mi
```

I saw there's an option for CPU cores, both `resources.limit.cpu` and `resources.requests.cpu` are available, but couldn't find anything for Memory.

If I set `executor.memory` that sets `resources.limits.memory`
