### ISSUE TITLE
Increasingly Memory Usage in Executer

### ISSUE THREAD

**Issue by arezvani** [kubeflow/spark-operator#1638]
Hi, 
I have set 
```
 executor:
   coreRequest: "500m"
   instances: 10
   memory: "5g"
   memoryOverhead: "10g"
```
but memory usage of executer increase until arrive to memory limit and my executer pods gets OOM.
What's the problem and how can I set spark usage never comes to memory limit and restrict that.
