### ISSUE TITLE
[Question]: How to add `sparkApplicationID` to the driver and executor pod names

### ISSUE THREAD

**Issue by vara-bonthu** [kubeflow/spark-operator#1681]
I am looking for an option to add `sparkApplicationId` to driver and executor pod names. This allows me to filter and structure the logs in S3 bucket with unique `sparkApplicationId`. I am planning to store the Spark Driver and Executor Logs under one folder with `sparkApplicationId`.

e.g., 
```
s3://spark-bucket/year=yyyy/month=mm/day=dd/<spark-application-id>/<app-name-driver>
s3://spark-bucket/year=yyyy/month=mm/day=dd/<spark-application-id>/<app-name-executor-1>
s3://spark-bucket/year=yyyy/month=mm/day=dd/<spark-application-id>/<app-name-executor-2> 
...
```

This is my config to add the Driver and Executor Pod names .

```yaml
sparkConf:
  # Naming the Driver and Executor pods
  "spark.app.name": "taxi-trip"
  "spark.kubernetes.driver.pod.name": "taxi-trip"
  "spark.kubernetes.executor.podNamePrefix": "taxi-trip" 
```

I am using FluentBit to export the Driver and Executor logs. So, I am able to store the logs as follows in S3 bucket.  

```
Driver → s3://spark-bucket/fluentbit-logs/taxi-trip/
Executor1 → s3://spark-bucket/fluentbit-logs/taxi-trip-exec-1/
Executor2 → s3://spark-bucket/fluentbit-logs/taxi-trip-exec-2/
...
```

I have also enabled the event logs to be written to S3 as shown in the below config

```yaml
sparkConf:
  "spark.eventLog.enabled": "true"
  "spark.eventLog.dir": "s3a://spark-bucket/spark-history-event-logs/"
```

Spark Operator creates a Event log file with the name of `sparkApplicationId`  as shown below. It will be easy to correlate the App logs and Event Logs if we can leverage sparkApplicationId to be used in driver and executor pods as well.

`s3://spark-bucket/spark-history-event-logs/*spark-0141a465e0ea4b5f97196987c204b63e*`

Another question... :) 

Currently my SparkHistoryServer setup only shows the Spark Events from the above file. I understand we can also view app logs for driver & executors from the Spark History Server. Does anyone know the required config to achieve this? 

You can see my full implementation here for the above setup https://awslabs.github.io/data-on-eks/docs/data-analytics/spark-operator-yunikorn.
