### ISSUE TITLE
[help] gcr.io/spark-operator/spark:v3.1.1 linux/arm64 image

### ISSUE THREAD

**Issue by mgyboom** [kubeflow/spark-operator#1790]
Such as the title.

**Comment by mgyboom** [comment]
And gcr.io/spark-operator/spark:v3.1.1-hadoop3 linux/arm64 image.

**Comment by jacobsalway** [comment]
I haven't been able to find where the `spark-operator/spark` images are being built or published from, but I've had success with the official Apache Spark images on Docker Hub (https://hub.docker.com/r/apache/spark/tags) which support both `arm64` and `amd64`. See the `image` config on the `SparkApplication` spec https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/api-docs.md#sparkapplication

For example:
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: apache/spark:3.4.1
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.1.1.jar
```
