### ISSUE TITLE
Spark Connect support

### ISSUE THREAD

**Issue by Dlougach** [kubeflow/spark-operator#1801]
It would be nice to either support [Spark Connect](https://spark.apache.org/docs/latest/spark-connect-overview.html) server natively within the Spark operator or at least provide a tutorial to on how to set it up (it supposedly substitutes driver).

**Comment by Wh1isper** [comment]
Hi, I've developed a module for deploying the latest 3.4.0 server-client model with support for direct PySpark Session connections!

Perhaps you could try this first, although it's based on native Spark's executor scheduling rather than Operator.

https://github.com/Wh1isper/sparglim#spark-connect-server-on-k8s

**Comment by whitleykeith** [comment]
@Dlougach If you wish to use the operator, there is a way.

First step, you need to make a wrapper class around the SparkConnectServer. For example:

```scala
package my.connect.server

import org.apache.spark.sql.connect.service.SparkConnectServer

object MyCoolSparkConnectServer {
  def main(args: Array[String]): Unit = {
   // you can initialize spark stuff here, the server will inherit the configs
    val connectServer = SparkConnectServer
    connectServer.main(args)
  }

}
```

This will circumvent the submission error you may have gotten if you tried to just run the `SparkConnectServer` directly. From my investigation that looks to be an arbitrary decision [within spark-submit](https://github.com/apache/spark/blob/add49b3c115f34ab8e693f7e67579292afface4c/core/src/main/scala/org/apache/spark/deploy/SparkSubmit.scala#L293-L294) that Cluster mode is "not applicable" to SparkConnect. Which is sort of true except when using this operator :) 

After that the job should spin up, but to get it working in-cluster you need to add a service component (you could just use the driver pod name directly but that feels icky to me)

```yaml
apiVersion: v1
kind: Service
metadata:
  name: <service-name>
spec:
  type: ClusterIP
  selector:
    spark-role: driver
    sparkoperator.k8s.io/app-name: <name-of-spark-app>
  ports:
    - name: grpc
      port: 15002
      targetPort: 15002
      protocol: TCP
```

With this you can use `sc://<service-name>.<spark-app-namespace>.svc.cluster.local:15002`. 

I also think that due to https://github.com/kubeflow/spark-operator/issues/1404, routing through Istio or other Service Mesh's might not work yet. Since the container port on the driver isn't passed to the pods I think Istio doesn't treat the route as GRPC. When trying to go through Istio ingress it hangs, though I haven't tried patching our CRDs yet.
