### ISSUE TITLE
Operator is not respawning driver pod if node is down or unreachable

### ISSUE THREAD

**Issue by manoj016** [kubeflow/spark-operator#1847]
We are trying to run one driver and 2 executors. We are facing issues while testing failover on the driver pod as it is not being respawned by the operator when the node is down. In the config also we have added tolerations to spawn in 3 seconds, but this config is not working.

The below config is used to spawn the above.

```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
  name: spark-telemetry
  namespace: default
spec:
  arguments:
    - /app-data/config-file/config.influx_timeseries_sink.yml
  driver:
    coreLimit: '2'
    cores: 2
    labels:
      version: 3.0.0
    memory: 6g
    serviceAccount: spark-operator-spark
    tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 3
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 3
    volumeMounts:
      - mountPath: /app-data
        name: telemetry-sink-data-pv-claim
      - mountPath: /app-data/config-file
        name: config-volume
  executor:
    coreLimit: '2'
    cores: 2
    instances: 2
    labels:
      version: 3.0.0
    memory: 4g
    tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 3
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 3
    volumeMounts:
      - mountPath: /app-data
        name: telemetry-sink-data-pv-claim
      - mountPath: /app-data/config-file
        name: config-volume
  image: docker.cloudsmith.io/quartic-dot-ai/docker/spark_influx_sink:3.10.0
  imagePullPolicy: Always
  imagePullSecrets:
    - docker-registry
  mainApplicationFile: local:///setup/jobs/spark-influx-sink_2.12.jar
  mainClass: ai.quartic.sink.influx.SparkInfluxSink
  mode: cluster
  restartPolicy:
    type: Always
    onFailureRetries: 1000000
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 1000
    onSubmissionFailureRetryInterval: 10
  sparkVersion: 3.0.0
  type: Scala
  volumes:
    - name: telemetry-sink-data-pv-claim
      persistentVolumeClaim:
        claimName: telemetry-sink-data-pv-claim
    - configMap:
        name: spark-config-timeseries
      name: config-volume

```
