### ISSUE TITLE
Support for Pod Topology Spread Constraints

### ISSUE THREAD

**Issue by xuzeng012** [kubeflow/spark-operator#1848]
Pod Topology Spread Constraints are important for enhancing high availability and fault tolerance by ensuring that pods are distributed across different topologies, such as nodes in different availability zones or failure domains. This feature would be highly beneficial for users who want to deploy Spark workloads in multi-zone or multi-cluster environments to improve reliability and resilience. Users should be able to configure constraints such as maxSkew, minDomains, topologyKey, and whenUnsatisfiable for Spark pods to ensure they are spread across different nodes and failure domains.

**Comment by ruhz3** [comment]
Spark Operator do support podAntiAffinity, so this is probably the best we can do for now.

```
spec:
  executor:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: spark-app-name
                operator: In
                values:
                - {{ your service name }}
            topologyKey: kubernetes.io/hostname
```

**Comment by korjek** [comment]
@ruhz3 podAntiAffinity can't be used as a replacement for TSC. For example, if you want to run 10 executor pods on at least two nodes, this can't be achieved with affinity.

**Comment by dyno** [comment]
another use case is we want to use 60% of spot instances to save cost, support `topologySpreadConstraints` would be handy.

**Comment by dyno** [comment]
we can use [pod-template](https://github.com/kubeflow/spark-operator/blob/master/examples/spark-pi-pod-template.yaml#L143) to workaround this problem, 
```
   template:
      metadata:
        labels:
          spark-app-name: mysparkapp
      spec:
        # XXX: has to list one container, otherwise it will fail with "org.apache.spark.SparkException: Could not load pod from template file."
        containers:
          - name: spark-kubernetes-executor
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: capacity-spread
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                spark-app-name: mysparkapp
            minDomains: 2
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: capacity-spread
                  operator: In
                  values: ["1", "6"]
```
