### ISSUE TITLE
Allow setting ephemeral-storage requests and limits on Pods

### ISSUE THREAD

**Issue by bscaleb** [kubeflow/spark-operator#1942]
I would like to be able to set `spec.containers[].resources.limits.ephemeral-storage` and `spec.containers[].resources.requests.ephemeral-storage` on the driver/executor Pods spawned by my `SparkApplication`. As far as I can tell, that is not possible. I see in this issue the user wants to do the same: https://github.com/kubeflow/spark-operator/issues/1546.

My use case is that I am running `SparkApplication` pods on Amazon EKS Fargate. The root volume of all Fargate Pods used to be fixed at 20GiB [but now supports variable requests and limits up to 175GiB](https://aws.amazon.com/cn/blogs/containers/amazon-eks-fargate-adds-support-for-larger-ephemeral-volumes/). These requests and limits are controlled by the two Pod spec values I mentioned above.

**Comment by cinesia** [comment]
Hi @bscaleb ,
I faced a similar problem about setting requests and limits on the ephemeral storage. There is a solution even tough is a bit tricky.

1. First define and create a `pod-template.yaml` ConfigMap with the desired quotas of the ephemeral storage and apply the manifests to the cluster. You can define a file for each ephemeral storage configurations.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-driver-pod-template-configmap
  namespace: default
data:
  template.yaml: |
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: spark-kubernetes-driver
        resources:
          requests:
            ephemeral-storage: "2Gi"
          limits:
            ephemeral-storage: "4Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-driver-executor-template-configmap
  namespace: default
data:
  template.yaml: |
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: spark-kubernetes-executor
        resources:
          requests:
            ephemeral-storage: "2Gi"
          limits:
            ephemeral-storage: "4Gi"
```

2. Install the Spark Operator mounting the ConfigMap as a volume using the values below.

```yaml
spark-operator:
  webhook:
    enable: true
  volumes:
    - name: spark-driver-pod-template-configmap
      configMap:
        name: spark-driver-pod-template-configmap
        items:
          - key: template.yaml
             path: spark-driver-pod-template.yaml
    - name: spark-executor-pod-template-configmap
      configMap:
        name: spark-executor-pod-template-configmap
        items:
          - key: template.yaml
             path: spark-executor-pod-template.yaml
  volumeMounts:
    - name: spark-driver-pod-template-configmap
       mountPath: /opt/spark/conf/spark-driver-pod-template.yaml
       subPath: spark-driver-pod-template.yaml
    - name: spark-executor-pod-template-configmap
       mountPath: /opt/spark/conf/spark-executor-pod-template.yaml
       subPath: spark-executor-pod-template.yaml
```

3. Apply the SparkApplication with the configuration described here(https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template).

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "<SPARK-OPERATOR-IMAGE" # <-- Change with a existing image !!!
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.4.0"
  sparkConf:
    spark.kubernetes.driver.podTemplateFile: /opt/spark/conf/spark-driver-pod-template.yaml  # <--- Must match the  mountPath of the volumeMounts                                                                                                 
    spark.kubernetes.executor.podTemplateFile: /opt/spark/conf/spark-executor-pod-template.yaml # <--- Must match the  mountPath of the volumeMounts                                                                                                 
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
```
Do not pay attention to the SparkApplication itself, but only to the `spec.sparkConf` section. 

Feel free to ask any question.
