### ISSUE TITLE
Set workdirectory

### ISSUE THREAD

**Issue by JWDobken** [kubeflow/spark-operator#1949]
I want the workdirectory to be inside my mounted volume, so when I run my application it can find local relative paths.

For example with `workingDir`:

```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: my-spark-job
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///mnt/myvolume/spark/applications/jobs/my-spark-job.py
  workingDir: local:///mnt/myvolume/spark/applications # <- throws error
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  volumes:
    - name: my-data
      persistentVolumeClaim:
        claimName: pvc-smb
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark
    volumeMounts:
      - name: my-data
        mountPath: /mnt
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
    volumeMounts:
      - name: my-data
        mountPath: /mnt
```
