### ISSUE TITLE
The spark operator does not need create, update and delete permissions for CustomResourceDefinition

### ISSUE THREAD

**Issue by ChenYi015** [kubeflow/spark-operator#1960]
The RBAC resources for the spark operator currently have permissions to `create`, `get`, `update` and `delete` `CustomResourceDefinition`:

https://github.com/kubeflow/spark-operator/blob/69e984135217146f321f46db9ab0fd1ee3340fcb/charts/spark-operator-chart/templates/rbac.yaml#L66-L74

However, permissions for `CustomResourceDefinition` are only required by Volcano scheduler integrated in spark operator, and it solely requires the `get` permission. 

https://github.com/kubeflow/spark-operator/blob/69e984135217146f321f46db9ab0fd1ee3340fcb/pkg/batchscheduler/volcano/volcano_scheduler.go#L176-L204

For enhanced security, it would be more appropriate to modify the permissions as follows:

```yaml
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
```
