### ISSUE TITLE
helm chart failed to render spark service account when extra annotations are specified

### ISSUE THREAD

**Issue by ChenYi015** [kubeflow/spark-operator#1966]
When extra spark serviceaccount annotations  are specified in `values.yaml`:

```yaml
serviceAccounts:
  spark:
    annotations: 
      key1: value1
      key2: value2
```

Helm will failed to render template:

```shell
$ helm template spark-operator charts/spark-operator-chart -f values.yaml
Error: YAML parse error on spark-operator/templates/spark-serviceaccount.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string
```
