### ISSUE TITLE
[QUESTION] spark-submit not called, and other questions

### ISSUE THREAD

**Issue by RyanZotti** [kubeflow/spark-operator#2011]
The main reason for this issue is that it seems my PySpark job is not running, and the reason that I think it's not running is that I don't see: 
* any of the typical logs boilerplate of Spark applications (lots of `INFO`, `WARN`, etc.)
* a `spark-submit` in the logs, which I had previously seen before I made a bunch of changes trying to fix permissions and image pull issues

Below are the steps to reproduce my problem. 

```
# Start with a fresh cluster
minikube start

# Add the repo
helm repo add spark-operator https://kubeflow.github.io/spark-operator

# Install the repo
helm install my-release spark-operator/spark-operator  \
    -f values.yaml \
    --namespace spark-operator \
    --create-namespace \
    --version 1.2.14

# Apply a variety of hacks I had to apply to get around permissions issues
kubectl apply -f trial-and-error-fixes.yaml

# Submit a job
kubectl apply -f spark-py-pi.yaml

# Get the driver's logs
kubectl logs pyspark-pi-driver -n spark-jobs
```

The logs of the driver, using the last command, show this:

> ++ id -u
> + myuid=0
> ++ id -g
> + mygid=0
> + set +e
> ++ getent passwd 0
> + uidentry=root:x:0:0:root:/root:/bin/bash
> + set -e
> + echo 0
> + echo 0
> + echo root:x:0:0:root:/root:/bin/bash
> 0
> 0
> root:x:0:0:root:/root:/bin/bash
> + [[ -z root:x:0:0:root:/root:/bin/bash ]]
> + exec /usr/bin/tini -s -- /usr/bin/spark-operator driver --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner local:///opt/spark/examples/src/main/python/pi.py

Where is the `spark-submit` command? I'm expecting the last two lines to be something like:

> + CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
> + exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=172.16.24.210 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class ...

Contents of `spark-py-pi.yaml`. I lightly adapted this from the file of the same name provided in the repo's `example` folder.

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: spark-jobs
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "kubeflow/spark-operator:v1beta2-1.4.5-3.5.0"
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0
```

`values.yaml`:
```
sparkJobNamespaces: ["spark-jobs"]
webhook:
  enable: true
image:
  repository: docker.io/kubeflow/spark-operator
  tag: v1beta2-1.4.5-3.5.0
spark:
  serviceAccountName: spark
rbac:
  createClusterRole: true
logLevel: 3
```

`trial-and-error-fixes.yaml`
```
apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: spark-jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: spark-jobs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: missing-kubeflow-permissions
rules:
  - apiGroups:
    - "sparkoperator.k8s.io"
    resources:
      - "sparkapplications"
      - "scheduledsparkapplications"
      - "sparkapplications/status"
    verbs:
      - "list"
      - "watch"
      - "update"
      - "get"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "events"
    verbs:
      - "list"
      - "create"
      - "patch"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: missing-kubeflow-permissions-role-binding
  namespace: spark-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: missing-kubeflow-permissions
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: spark-jobs

```

And while I'm here, I had several other totally unrelated questions I wanted to ask but couldn't find answers to on Google, Stack Overflow or in the docs:
* I'm new to Kubernetes. Does the Spark Operator support two separate images, one for the operator itself and the other for my Spark application? 
* What is the relationship between a chart version and an image tag? They're 1-1 correct?
* What do the `logLevel` numbers map to? Is there a way to circumvent the magic numbers and explicitly specify the level, e.g., `INFO` or `DEBUG`?
