### ISSUE TITLE
[QUESTION] Error related with webhook 

### ISSUE THREAD

**Issue by alstjs37** [kubeflow/spark-operator#2032]
Hello,

I've just encountered an error like this,

When I first installed the spark-operator and run `pyspark-pi.py` without giving the `--set webhook.enable=true` option, 
I checked it worked well.

After that, in order to mount the volume, I removed the spark-operator with `helm uninstall` and reinstalled it again by giving the `--set webhook.enable=ture` option, but pyspark-pi does not work now.

My pods in spark-operator namespace
```bash
$ sudo kubectl get all -n spark-operator

NAME                                                  READY   STATUS      RESTARTS   AGE
pod/sparkoperator-spark-operator-6994c8bcfd-vns8k     1/1     Running     0          137m
pod/sparkoperator-spark-operator-webhook-init-ww2lw   0/1     Completed   0          137m

NAME                                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/sparkoperator-spark-operator-webhook   ClusterIP   10.107.69.123   <none>        443/TCP   137m

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sparkoperator-spark-operator   1/1     1            1           137m

NAME                                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/sparkoperator-spark-operator-6994c8bcfd   1         1         1       137m

NAME                                                  STATUS     COMPLETIONS   DURATION   AGE
job.batch/sparkoperator-spark-operator-webhook-init   Complete   1/1           3s         137m
```

when i apply yaml file to k8s with below file, 
i got `SUBMISSION_FAILED` from sparkapplication ...

here is my pyspark-pi.yaml
```yaml
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "msleedockerhub/spark-py:py3.0"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.1
    serviceAccount: sparkoperator-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.1
```

I'm sure there's no problem with the image I created.
If you set up the webhook, what else should I set up in the yaml file?

How can i solve this problem?
plz help
