### ISSUE TITLE
[BUG] Executor run error

### ISSUE THREAD

**Issue by zhang5059T** [kubeflow/spark-operator#2057]
## Description
driver submit a job

Execute will have an action of copying the JAR package

24/06/13 08:53:59 INFO Utils: Copying /opt/seatunnel/connectors/connector-console-2.3.5.jar to /var/data/spark-e61eb1cc-b318-4d4e-bb4e-279c4f545c9e/spark-508ad592-a75f-45c9-a1f9-021709e26a25/3768210091718268322489_cache
24/06/13 08:53:59 INFO Utils: Copying /var/data/spark-e61eb1cc-b318-4d4e-bb4e-279c4f545c9e/spark-508ad592-a75f-45c9-a1f9-021709e26a25/3768210091718268322489_cache to **/opt/./c**onnector-console-2.3.5.jar

When copying for the second time, the path seems a bit wrong. Could it be caused by my incorrect configuration file?

## Driver and Executor  cfg
```
driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.0
    serviceAccount: spark-release-spark-operator
    env:
      - name: SEATUNNEL_HOME
        value: "/opt/seatunnel"
    volumeMounts:
      - name: seatunnel-oracle
        mountPath: /data/v2.oracle.conf
        subPath: v2.oracle.conf
executor:
   cores: 1
   instances: 1
   memory: "512m"
   labels:
     version: 3.3.0
   volumeMounts:
     - name: seatunnel-oracle
       mountPath: /data/v2.oracle.conf
       subPath: v2.oracle.conf
```
I want to know why there are two copying actions, and whether the second copying needs to be combined with an environment variable.
