### ISSUE TITLE
sparkApplication immediately deleted if an ownerReference is set (Argo Workflows)

### ISSUE THREAD

**Issue by Aransh** [kubeflow/spark-operator#2090]
## Description
I am working on integrating Argo Workflows with the Spark Operator.
Everything is working properly, Argo Workflows deploys the Spark Application and properly tracks it to completion.

My problem lies in visibility:
 In order to properly "link" the deployed SparkApplication to my Workflow (and therefor allow me to easily see logs for it on ArgoCD), I need to create an ownerReference in it.
This is supported in Argo Workflows by setting "setOwnerReference: true" on the step that creates the SparkApplication.
Upon initial tests I have seen this doesn't seem to work as expected, as the SparkApplication is created and then immediately deleted...
After some research I found that everything works properly UNLESS I enable setOwnerReference.

At this point I tried a more manual approach to rule out the issue being related to Argo Workflows specifically, and tried manually adding an owner reference to a SparkApplication resource (using kubectl edit), and indeed as soon as I add the reference, the SparkApplication is immediately deleted.

So while this issue is related to Argo Workflows integration, the underlying issue here is that the spark operator appears to immediately remove a SparkApplication if an ownerReference is added to it.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

1. Create any SparkApplication
2. Edit it and add a standard Kubernetes ownerReferences field, could be to any external resource
3. The SparkApplication will be immediately removed

Or with Argo Workflows:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo-workflows
  name: test-argo-workflow
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  templates:
  - name: main
    steps:
      - - name: cr-ml-b4-pre-agg-test
          template: spark-cr-ml-b4-pre-agg-test
  - name: spark-cr-ml-b4-pre-agg-test
    resource:
      action: apply
      setOwnerReference: true
      successCondition: status.applicationState.state == COMPLETED
      failureCondition: status.applicationState.state == FAILED
      manifest: |
        apiVersion: sparkoperator.k8s.io/v1beta2
        kind: SparkApplication
        metadata:
          name: cr-ml-b4-pre-agg-test
          namespace: spark-apps
        spec:
         < input any spark app spec >
```
## Expected behavior

The SparkApplication continues to run, with the OwnerReference in place as a "Link" for external resources to track it's lifecycle

## Actual behavior

The SparkApplication is immediately removed

### Terminal Output Screenshot(s)

> spark-operator-qa-1-7b4bfb66b8-nx2st spark-operator I0722 09:37:01.606379      10 spark_pod_eventhandler.go:77] Pod workflow-poc-cr-ml-b4-pre-agg-driver deleted in namespace spark-apps.
> spark-operator-qa-1-7b4bfb66b8-nx2st spark-operator I0722 09:37:01.609087      10 event.go:364] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-apps", Name:"workflow-poc-cr-ml-b4-pre-agg", UID:"80a0afcd-13d8-4b1f-9c5f-7d8c9a55dc09", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"649228998", FieldPath:""}): type: 'Normal' reason: 'SparkApplicationDeleted' SparkApplication workflow-poc-cr-ml-b4-pre-agg was deleted

## Environment & Versions

- Spark Operator App version: v1beta2-1.6.1-3.5.0
- Helm Chart Version: 1.4.3
- Kubernetes Version: 1.28
