### ISSUE TITLE
[BUG] configmap not mounted with scheduledsparkapplication

### ISSUE THREAD

**Issue by gwenael-lebarzic** [kubeflow/spark-operator#2112]
## Description
Creates a configmap from a configuration file. 
Then creates a SparkApplication with the configmap mounted.
Use helm to install the SparkApplication, it works fine, the configmap is mounted on the driver pod.

Create a ScheduledSparkApplication with the configmap mounted.
When the pod for the spark application driver is created, the configmap is not mounted.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.
I saw some issues related to problem with mounting configMaps, but each time, I have the impression it was global. For my case, the mounting of configmaps works well for SparkApplications, but does not work for ScheduledSparkApplications

## Reproduction Code [Required]

The configmap :
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-conf
data:
  application.conf: |
    spark {
      app.name = "my-spark-application"
      master = "k8s://https://mycontrolplane:443"
    }
```

The ScheduledSparkApplication :
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: "ScheduledSparkApplication"
metadata:
  name: my-scheduled-app
  namespace: my-namespace
spec:
  schedule: "@every 5m"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 1
  failedRunHistoryLimit: 3
  template:
    driver:
      cores: 1
      coreLimit: "1200m"
      env:
      javaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Dcom.amazonaws.sdk.disableCertChecking=true"
      labels:
        version: 3.3.1
      memory: "2g"
      serviceAccount: spark
      volumeMounts:
        - name: config-vol
          mountPath: /etc/myfolder
    executor:
      cores: 1
      coreLimit: "1200m"
      env:
      instances: 1
      javaOptions: "-Dcom.amazonaws.services.s3.enableV4=true -Dcom.amazonaws.sdk.disableCertChecking=true"
      labels:
        version: 3.3.1
      memory: "2g"
      serviceAccount: spark
      volumeMounts:
        - name: config-vol
          mountPath: /etc/myfolder
    hadoopConf: {}
    image: myimage;myversion
    imagePullPolicy: "Always"
    mainApplicationFile: s3a://mybucket/myscalaproject.jar
    mainClass: "myclass"
    mode: "cluster"
    restartPolicy:
      type: "Never"
    sparkConf: {}
    sparkVersion: "3.3.1"
    type: "Scala"
    volumes:
      - name: config-vol
        configMap:
          name: my-conf
```

Here is a partial describe on the spark operator pod :
```
Containers:
  spark-operator:
    Container ID:  (...)
    Image:         spark-operator:v1beta2-1.3.8-3.1.1
    Port:          8090/TCP
    Host Port:     0/TCP
    Args:
      -v=2
      -logtostderr
      -namespace=my-namespace
      -enable-ui-service=true
      -ingress-url-format=
      -controller-threads=10
      -resync-interval=30
      -enable-batch-scheduler=false
      -label-selector-filter=
      -enable-metrics=true
      -metrics-labels=app_type
      -metrics-port=8090
      -metrics-endpoint=/metrics
      -metrics-prefix=
      -enable-webhook=true
      -webhook-svc-namespace=my-operator-namespace
      -webhook-port=443
      -webhook-timeout=30
      -webhook-svc-name=spark-operator-webhook
      -webhook-config-name=spark-operator-webhook-config
      -webhook-namespace-selector=
      -enable-resource-quota-enforcement=false
```

When pod is created, the volumes part of pod description looks like this :
```
Volumes:
  spark-local-dir-1:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  spark-conf-volume-driver:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      spark-drv-217ed491131044b1-conf-map
    Optional:  false
  kube-api-access-6zftw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
```

And, in the container.mount part of the pod description:
```
    Mounts:
      /opt/spark/conf from spark-conf-volume-driver (rw)
      /var/data/spark-bc9e3b78-2d96-4204-8723-a7281f758356 from spark-local-dir-1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-6zftw (ro)
```

1. Create a configmap
2. Add volumes and volumeMounts in a scheduledSparkApplication

## Expected behavior

VolumeMount should be mounted on driver pod and executor pods.

## Actual behavior

VolumeMount is not mounted neither on driver pod nor on executors pods.

## Environment & Versions

- Spark Operator App version: v1beta2-1.3.8-3.1.1
- Helm Chart Version: spark-operator-1.1.28
- Kubernetes Version: v1.27.6-gke.2500
- Apache Spark version: 3.3.1

Thank you in advance for your help !

Best regards.
