### ISSUE TITLE
If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials

### ISSUE THREAD

**Issue by m-gavrilyuk** [kubeflow/spark-operator#2130]
If I specify `mainApplicationFile: http://<some_url>` and the url has basic auth, how do I specify the credentials

_Originally posted by @Nj-kol in https://github.com/kubeflow/spark-operator/issues/350#issuecomment-1693173161_

**Comment by ChenYi015** [comment]
@m-gavrilyuk Have you tried `https://user:password@host/path/to/file`? This is not safe, but might work. Ref: https://spark.apache.org/docs/latest/submitting-applications.html#advanced-dependency-management.

**Comment by m-gavrilyuk** [comment]
> @m-gavrilyuk Have you tried `http://user:password@host/path/to/file`? This is not safe, but might work. Ref: https://spark.apache.org/docs/latest/submitting-applications.html#advanced-dependency-management.

Yes I tried 
This doesn't work

**Comment by m-gavrilyuk** [comment]
I did a little research and came up with some very strange behavior
if I specify
```yaml
spec:
  deps:
    packages:
      - my-group:my-app:my-version
    repositories:
      - "https://my-nexus.com/repository/mvn__snapshots/"
  mainApplicationFile: "https://my-nexus.com/repository/mvn__snapshots/.../my-app.jar
  sparkConf:
    spark.jars.ivySettings: "/opt/spark/conf/ivysettings.xml"
    spark.jars.ivy: "/opt/spark/.ivy2"
```
and get configmap to operator with ivysettings.xml 
all work fine 
all jars download 
But I'm using a FAT jar with all the dependencies inside.
And the package references the pom file that specifies the dependencies.
spark download my FAT jar from mainApplicationFile link and download tini jar with all dependencies which I don't need
but if i delete deps: block i have 401 error
