### ISSUE TITLE
[BUG] spark-operator 2.0.0.rc.0: Volumes defined in SparkApplication are not added to pods

### ISSUE THREAD

**Issue by tcassaert** [kubeflow/spark-operator#2162]
## Description
Please provide a clear and concise description of the issue you are encountering, and a reproduction of your configuration.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

Installed the spark-operator with following Helm values (I did use the latest Helm chart):
```yaml
---
image: # Custom built image from commit c810ece25b2b69af586a9bda289bce0842ac7dbf
controller:
  batchScheduler:
    enable: true
  podMonitor:
    create: true
spark:
  jobNamespaces:
    - ""
```
Both webhook and controller are running.

Running following SparkApplication:

```yaml
---
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-yunikorn
  namespace: spark-jobs-dev
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.0
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.5.0.jar
  sparkVersion: 3.5.0
  driver:
    labels:
      version: 3.5.0
      role: driver
    cores: 1
    coreLimit: 1200m
    memory: 512m
    serviceAccount: openeo
    volumeMounts:
      - mountPath: /opt/prometheus_config.yaml
        name: prometheus-configmap
        subPath: prometheus_config.yaml
  executor:
    labels:
      version: 3.5.0
    instances: 5
    cores: 1
    coreLimit: 1200m
    memory: 1024m
  batchScheduler: yunikorn
  batchSchedulerOptions:
    queue: root.cdse-dev
  volumes:
    - configMap:
        name: prometheus-config
      name: prometheus-configmap
```
The ConfigMap exists in the cluster.

The resulting driver pod has following volumeMounts:

```yaml
    volumeMounts:
    - mountPath: /var/data/spark-4f4ca4ff-c9c9-408d-b58a-a57114537b4e
      name: spark-local-dir-1
    - mountPath: /opt/spark/conf
      name: spark-conf-volume-driver
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n2kw9
      readOnly: true
```
and volumes:
```yaml
  volumes:
  - emptyDir: {}
    name: spark-local-dir-1
  - configMap:
      defaultMode: 420
      items:
      - key: spark.properties
        mode: 420
        path: spark.properties
      name: spark-drv-1832ab91daaedbe1-conf-map
    name: spark-conf-volume-driver
  - name: kube-api-access-n2kw9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

## Expected behavior

I expected the resulting driver pod to have the volumes and volumeMounts defined.

## Actual behavior

The pod does not have the additional volumeMounts or volumes defined.
Running the webhook with `--log-level=debug` did not really reveal anything.

## Environment & Versions

- Spark Operator App version: v2.0.0-rc.0
- Helm Chart Version: v2.0.0-rc.0
- Kubernetes Version: 1.25.7
- Apache Spark version: 3.5.0
