### ISSUE TITLE
[BUG] RBAC issue with V2.0.0

### ISSUE THREAD

**Issue by Aransh** [kubeflow/spark-operator#2185]
## Description

Have attempted upgrading to Chart V2 today, stumbled into issues with RBAC for the controller.

- [v] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code

Deploy the spark operator with the following values:
(on namespace "operator-spark", to control sparkApplications on namespace "spark-apps")
```
controller:
  replicas: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: spark-operator
            app.kubernetes.io/component: controller
  serviceAccount:
    name: "operator-spark"

spark:
  serviceAccount:
    name: "spark-apps"
  jobNamespaces: ["", "spark-apps"]

webhook:
  replicas: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: spark-operator
            app.kubernetes.io/component: webhook
```

## Expected behavior

Spark operator is deployed with RBAC resources, allowing me to deploy sparkApplications to namespace "spark-apps".

Will mention a corresponding values.yaml was used with the previous version and worked as expected:

```
replicaCount: 3
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: kubernetes.io/hostname
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: spark-operator
serviceAccounts:
  spark:
    name: "spark-apps"
  sparkoperator:
    name: "operator-spark"
sparkJobNamespaces: ["spark-apps"]
webhook:
  enable: true
```

Main difference is I've added "" to spark.jobNamespaces as described in the V2.0.0 release notes - https://github.com/kubeflow/spark-operator/releases/tag/v2.0.0

## Actual behavior

Spark operator successfully starts, RBAC resources are created, but the controller itself is missing permissions for configmaps on the target namespace.
As soon as a sparkApplication is deployed, no pods are deployed, and these errors come up in the operator logs:
```
W0923 12:21:16.679003      10 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:operator-spark:operator-spark" cannot list resource "configmaps" in API group "" in the namespace "spark-apps"
E0923 12:21:16.679034      10 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.3/tools/cache/reflector.go:229: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:operator-spark:operator-spark" cannot list resource "configmaps" in API group "" in the namespace "spark-apps"
```

## Environment & Versions

- Spark Operator App version: 2.0.0
- Helm Chart Version: 2.0.0
- Kubernetes Version: 1.30
- Apache Spark version: 3.5.1

## Additional context

* Have attempted to install the operator on the same namespace as the sparkApplications
* Attempted to add the "operator-spark" namespace to spark.jobNamespaces
* Attempted with and without "" in spark.jobNamespaces

Only solution that worked was reverting to chart version [1.4.6](https://github.com/kubeflow/spark-operator/releases/tag/spark-operator-chart-1.4.6) (with the configuration mentioned under "Expected behavior") 

Please let me know if any more info is needed, we're really eager to move to V2 as it supposed to resolved many of the issues we are currently experiencing
