### ISSUE TITLE
spark job using SparkOperator - Error: Could not find or load main class org.apache.spark.launcher.Main

### ISSUE THREAD

**Issue by karanalang** [kubeflow/spark-operator#2200]
I've Spark deployed on GKE (using SparkOperator), and am deploying a spark job which requires dependancies and certs .. and am running into issues, error is shown below :

```
(base) Karans-MacBook-Pro:spark-k8s-operator karanalang$ kc logs -f structured-streaming-debug-1727474395-driver -n spark-operator
Error: Could not find or load main class org.apache.spark.launcher.Main
Caused by: java.lang.ClassNotFoundException: org.apache.spark.launcher.Main
/opt/spark/bin/spark-class: line 97: CMD: bad array subscript
``` 

Here is the Dockerfile used to create the Docker image:

```
# Use an official Apache Spark base image
FROM apache/spark:3.5.0

# Switch to root user to install additional dependencies
USER root

# Set the working directory
WORKDIR /opt/spark/work-dir

# Set environment variables
ENV SPARK_HOME /opt/spark
ENV PATH $PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin
ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.5-src.zip:$PYTHONPATH


RUN mkdir -p /opt/spark/custom-dir
RUN mkdir -p /opt/spark/conf

# Copy your application files, dependencies, params files into custom-dir
COPY custom-dir /opt/spark/custom-dir/

RUN ls -l /opt/spark/custom-dir

COPY gcs-connector-hadoop3-latest.jar /opt/spark/jars/

COPY jars/* /opt/spark/jars/

# Set correct permissions
RUN chown -R spark:spark /opt/spark/custom-dir /opt/spark/conf /opt/spark/jars && \
    chmod -R 755 /opt/spark/conf /opt/spark/jars /opt/spark/custom-dir

# Switch back to spark user
USER spark

```

```
# yaml to deploy the job

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: structured-streaming-debug-{{ now | unixEpoch }}
  namespace: spark-operator
spec:
  type: Python
  mode: cluster
  image: "{{ .Values.image }}"
  imagePullPolicy: Always
  imagePullSecrets:
    - {{ .Values.imagePullSecret }}
  mainApplicationFile: "local:///opt/spark/custom-dir/StructuredStream-on-gke.py"
  sparkVersion: "{{ .Values.sparkVersion }}"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: {{ .Values.driver.cores }}
    coreLimit: "{{ .Values.driver.coreLimit }}"
    memory: "{{ .Values.driver.memory }}"
    labels:
      version: "{{ .Values.sparkVersion }}"
    serviceAccount: spark
    volumeMounts:
      - name: gcs-key
        mountPath: /etc/secrets
        readOnly: true
      - name: spark-jars
        mountPath: /opt/spark/jars
        readOnly: true
    initContainers:
    - name: debug-container
      image: "{{ .Values.image }}"
      command: ["/bin/sh", "-c"]
      args:
      - |
        echo "Debugging Spark installation:"
        ls -l /opt/spark/bin/spark-submit
        ls -l /opt/spark/jars/gcs*
        echo "JAVA_HOME: $JAVA_HOME"
        echo "SPARK_HOME: $SPARK_HOME"
        echo "PATH: $PATH"
        java -version
        echo "Checking for main application file:"
        ls -l /opt/spark/custom-dir
        if [ -f /opt/spark/custom-dir/StructuredStream-on-gke.py ]; then
          echo "Main application file found"
          cat /opt/spark/custom-dir/StructuredStream-on-gke.py
        else
          echo "Main application file not found"
        fi
        echo "Attempting to launch Spark application:"
        $SPARK_HOME/bin/spark-submit --class org.apache.spark.deploy.SparkSubmit --master k8s://https://kubernetes.default.svc --deploy-mode cluster --name test-app --conf spark.kubernetes.container.image={{ .Values.image }} --conf spark.kubernetes.namespace=spark-operator local:///opt/spark/custom-dir/StructuredStream-on-gke.py
  executor:
    cores: {{ .Values.executor.cores }}
    instances: {{ .Values.executor.instances }}
    memory: "{{ .Values.executor.memory }}"
    labels:
      version: "{{ .Values.sparkVersion }}"
    volumeMounts:
      - name: gcs-key
        mountPath: /etc/secrets
        readOnly: true
      - name: spark-jars
        mountPath: /opt/spark/jars
        readOnly: true
  volumes:
    - name: gcs-key
      secret:
        secretName: {{ .Values.gcsKeySecret }}
    - name: spark-jars
      persistentVolumeClaim:
        claimName: {{ .Values.pvc.name }}
  deps:
    jars:
      - local:///opt/spark/jars/*.jar
    pyFiles:
      - local:///opt/spark/custom-dir/streams.zip
      - local:///opt/spark/custom-dir/utils.zip
    files:
      - local:///opt/spark/custom-dir/syslog-vani-prefix.p12
      - local:///opt/spark/custom-dir/versa-alarmblock-test-user.p12
      - local:///opt/spark/custom-dir/versa-appstat-test-user.p12
      - local:///opt/spark/custom-dir/versa-bandwidth-test-user.p12
      - local:///opt/spark/custom-dir/intfutil-user-test.p12
      - local:///opt/spark/custom-dir/alarm-compression-user-test.p12
      - local:///opt/spark/custom-dir/alarmblock-user-test.p12
      - local:///opt/spark/custom-dir/appstat-agg-user-test.p12
      - local:///opt/spark/custom-dir/appstat-anomaly-user-test.p12
      - local:///opt/spark/custom-dir/appstats-user-test.p12
      - local:///opt/spark/custom-dir/insights-user-test.p12
      - local:///opt/spark/custom-dir/params.cfg
      - local:///opt/spark/custom-dir/params_password.cfg
  pythonVersion: "{{ .Values.pythonVersion }}"
  sparkConf:
    "spark.kubernetes.namespace": "spark-operator"
    "spark.kubernetes.authenticate.driver.serviceAccountName": "spark"
    "spark.kubernetes.container.image": "{{ .Values.image }}"
    "spark.kubernetes.driver.container.image": "{{ .Values.image }}"
    "spark.kubernetes.executor.container.image": "{{ .Values.image }}"
    "spark.hadoop.fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "spark.hadoop.fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    "spark.hadoop.google.cloud.auth.service.account.enable": "true"
    "spark.hadoop.google.cloud.auth.service.account.json.keyfile": "/etc/secrets/spark-gcs-key.json"
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "{{ .Values.sparkEventLogDir }}"
    "spark.hadoop.fs.gs.auth.type": "SERVICE_ACCOUNT_JSON_KEYFILE"
    "spark.dynamicAllocation.enabled": "true"
    "spark.dynamicAllocation.executorIdleTimeout": "120s"
    "spark.shuffle.service.enabled": "true"
    "spark.kubernetes.executor.deleteOnTermination": "false"
    "spark.jars": "/opt/spark/jars/*.jar"
  hadoopConf:
    "fs.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem"
    "fs.AbstractFileSystem.gs.impl": "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS"
    "google.cloud.auth.service.account.enable": "true"
    "google.cloud.auth.service.account.json.keyfile": "/etc/secrets/spark-gcs-key.json"
  arguments:
    - "--isdebug={{ .Values.isdebug }}"

```

I've added an initContainer to check if the application files are there in the custom-dir, output of this 

```
(base) Karans-MacBook-Pro:spark-k8s-operator karanalang$ kc logs -f structured-streaming-debug-1727474395-driver -n spark-operator -c debug-container
Debugging Spark installation:
-rwxr-xr-x 1 spark spark 1040 Sep  9  2023 /opt/spark/bin/spark-submit
-rwxr-xr-x 1 spark spark 40713341 Sep 25 19:24 /opt/spark/jars/gcs-connector-hadoop3-latest.jar
JAVA_HOME: /opt/java/openjdk
SPARK_HOME: /opt/spark
PATH: /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/spark/bin:/opt/spark/sbin
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode, sharing)
Checking for main application file:
total 172
...
-rwxr-xr-x 1 spark spark 17301 Sep 26 06:40 main.py
-rwxr-xr-x 1 spark spark 69057 Sep 25 19:16 streams.zip
-rwxr-xr-x 1 spark spark   556 Sep 16 22:57 StructuredStream-on-gke.py
-rwxr-xr-x 1 spark spark  7064 Sep 25 19:16 utils.zip
Main application file found

```

so, seems like the required files are there

any ideas why Spark is not able to find the main file when it deploys the application ?

tia!
