### ISSUE TITLE
[BUG] minor: Several `sparkUIOptions` have become required

### ISSUE THREAD

**Issue by Tom-Newton** [kubeflow/spark-operator#2215]
## Description
It looks like the defaults for `spec.sparkUIOptions.servicePort`, `spec.sparkUIOptions.servicePortName` and `spec.sparkUIOptions.serviceType` have stopped working somewhere between 1.1.27 to 2.0.1 and omitting them now causes a config validation error when creating a `SparkApplication`. 

However if I omit these

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]
Use the following yaml config 
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: test
spec:
  image: "dummy"
  mainApplicationFile: "dummy"
  mode: cluster
  type: Python
  sparkUIOptions:
    ingressTLS:
    - hosts:
      - '*.dummy'
      secretName: spark-ui-tls-secret
  sparkVersion: 3.5.0
```

Run `kubectl apply -f <yaml file containing the above content>`

## Expected behavior
Looking at the docs and the code it looks like these are still supposed to be optional 
https://github.com/kubeflow/spark-operator/blob/master/docs/api-docs.md#sparkuiconfiguration
https://github.com/kubeflow/spark-operator/blob/1972fb75d273de2587731b78f8dbea3d9ae6c5a2/api/v1beta2/sparkapplication_types.go#L280-L291 Therefore I would expect the spark application to be successfully created using the defaults. 

## Actual behavior
Get the below error:
```
The SparkApplication "test" is invalid: 
* spec.sparkUIOptions.servicePort: Invalid value: "null": spec.sparkUIOptions.servicePort in body must be of type integer: "null"
* spec.sparkUIOptions.servicePortName: Invalid value: "null": spec.sparkUIOptions.servicePortName in body must be of type string: "null"
* spec.sparkUIOptions.serviceType: Invalid value: "null": spec.sparkUIOptions.serviceType in body must be of type string: "null"
```

## Environment & Versions

- Spark Operator App version: 2.0.1
- Helm Chart Version: 2.0.1
- Kubernetes Version: 1.29.7
- Apache Spark version: 3.5.0

## Additional context
This can easily be worked around by explicitly setting the defaults
```
    servicePortName: spark-driver-ui-port
    servicePort: 4040
    serviceType: ClusterIP
```
I think its probably still worth reporting this as it is a little annoying and I suspect it could confuse new users.
