### ISSUE TITLE
[FEATURE] Allow spark-operator-controller and spark-operator-webhook pods to run without root

### ISSUE THREAD

**Issue by npgretz** [kubeflow/spark-operator#2218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

Our DevOpsSec team requires us to run k8's apps with a securityContext that removes root privileges before being able to deployed them to environments with access to data. I want to be able to deploy the spark-operator Helm chart with the following (container)securityContext for the controller and webhook pods:
```
securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    runAsUser: 1000 # chosen from example chart values
    runAsGroup: 2000 # chosen from example chart values
    capabilities:
      drop:
      - ALL
```

#### Describe the solution you would like

I want to be able to deploy the spark-operator Helm chart with the following (container)securityContext for the controller and webhook pods:
```
securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    runAsUser: 1000 # chosen from example chart values
    runAsGroup: 2000 # chosen from example chart values
    capabilities:
      drop:
      - ALL

```
#### Describe alternatives you have considered

Not being able to run the spark-operator app.

#### Additional context

I can run the example spark-python-pi.yaml with the Webhook using the following securityContext if I create a directory /etc for the Webhook to create certs in:

```

# Webhook
  volumes:
    - name: etc
      emptyDir:
        sizeLimit: 500Mi
  volumeMounts:
    - name: etc
      mountPath: /etc/k8s-webhook-server/serving-certs
      subPath: serving-certs
      readOnly: false

securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    runAsUser: 1000 # chosen from example chart values
    runAsGroup: 2000 # chosen from example chart values
    capabilities:
      drop:
      - ALL
```

But for the Controller pod, I am able to run with `readOnlyRootFilesystem: true` if I add a /tmp directory to the controller pod:

```
# Controller
volumes:
    - name: tmp-dir
      emptyDir:
        sizeLimit: 1Gi
  volumeMounts:
    - name: "tmp-dir"
      mountPath: "/tmp"

```

Once, I stop the Controller from running as root though, I get an error that krb5.conf is not specified:

<img width="1238" alt="Screenshot 2024-10-03 at 13 08 38" src="https://github.com/user-attachments/assets/badc4f82-1dac-4a81-b94d-9599d3838d27">

**Comment by npgretz** [comment]
Sorry for the lack of context to reproduce my error in my original post; I had to leave before finishing it.

The smallest example to reproduce the error is to deploy the default Helm chart with these settings:
```
controller:
  securityContext:
    runAsUser: 1000 # Any UID besides 185 (spark from the Docker image)
```
This will trigger an error: "basedir must be absolute: ?/.ivy2/local" because the arbitrary user does not have a home directory. I solved this by mounting an empty dir in the spark application yaml:
```
#spark-python-pi.yaml

sparkConf:
	“spark.jars.ivy”: “/.ivy2”
volumes:
    - name: ivy-home
      emptyDir:
        sizeLimit: 500Mi
driver:
    volumeMounts:
      - name: "ivy-home"
        mountPath: "/.ivy2"
```

After doing this, you will get the krb5.conf missing error in my initial error post.


I was actually able to run the controller and webhook containers without root privilege (outside of NET_BIND_SERVICE capability which is already being addressed) with these settings:
```
controller:
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    runAsUser: 185
    runAsGroup: 2000
    capabilities:
      drop:
      - ALL
      add: ["NET_BIND_SERVICE"]

webhook:
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    runAsUser: 1000
    runAsGroup: 2000
    capabilities:
      drop:
      - ALL
      add: ["NET_BIND_SERVICE"]
```


It seems like this issue is able to be resolved if a user is willing to run the controller container as UID: 185:spark. I would propose changing the comments below `controller.podSecurityContext`and `controller.securityContext` that suggest the controller could be run with UID 1000:
```
# -- Security context for controller pods.
  podSecurityContext: {}
    # runAsUser: 1000
    # runAsGroup: 2000
    # fsGroup: 3000

# -- Security context for controller containers.
  securityContext: {}
    # runAsUser: 1000
    # runAsGroup: 2000
    # fsGroup: 3000
```
