### ISSUE TITLE
[BUG] secret not getting mounted as VolumeMount 

### ISSUE THREAD

**Issue by karanalang** [kubeflow/spark-operator#2220]
## Description

My pyspark application needs to access GCP storage bucket, and i've mounted the secret (containing the service account key) as volume mount .. however getting an error.

```
Traceback (most recent call last):
  File "/opt/spark/custom-dir/main.py", line 412, in <module>
    sys.exit(main())
  File "/opt/spark/custom-dir/main.py", line 400, in main
    spark = SparkSession.builder.appName('StructuredStreaming_Vani_main').getOrCreate()
  File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/session.py", line 497, in getOrCreate
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 515, in getOrCreate
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 203, in __init__
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 296, in _do_init
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 421, in _initialize_context
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1587, in __call__
  File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.io.FileNotFoundException: /mnt/secrets/spark-gcs-key.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at java.base/java.io.FileInputStream.<init>(Unknown Source)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromJsonKeyFile(CredentialFactory.java:297)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredential(CredentialFactory.java:414)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1479)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1638)

``` 

here is the yaml :

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: structured-streaming-350-{{ now | unixEpoch }}
  namespace: so350
spec:
  type: Python
  mode: cluster
  sparkVersion: "3.5.0"
  image: "us-east1-docker.pkg.dev/versa-kafka-poc/spark-job-repo/ss-main-so350:3.5.0"
  imagePullPolicy: Always
  imagePullSecrets:
    - gcr-json-key
  mainApplicationFile: "local:///opt/spark/custom-dir/main.py"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  
  driver:
    cores: {{ .Values.driver.cores }}
    coreLimit: "{{ .Values.driver.coreLimit }}"
    memory: "{{ .Values.driver.memory }}"
    labels:
      version: 3.5.0
    serviceAccount: spark
    securityContext:
      runAsUser: 185  # UID for spark user
    volumeMounts:
      - name: gcs-key
        mountPath: /mnt/secrets
        readOnly: true
    initContainers:
    - name: init1
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
    - name: init2
      image: busybox
      command:
        - /bin/sh
          - "-c"
          - |
            echo "Checking mounted secrets";
            ls -l /mnt/secrets;
            cat /mnt/secrets/spark-gcs-key.json;
            sleep 180; # Keep the init container running for inspection
    
  executor:
    cores: {{ .Values.executor.cores }}
    instances: {{ .Values.executor.instances }}
    memory: "{{ .Values.executor.memory }}"
    labels:
      version: "3.5.0"
    securityContext:
      runAsUser: 185  # UID for spark user
    volumeMounts:
      - name: gcs-key
        mountPath: /mnt/secrets
        readOnly: true
  volumes:
    - name: gcs-key
      secret:
        secretName: spark-gcs-creds

```

spark-events  show  -> MountVolume.SetUp failed for volume "spark-conf-volume-driver" : configmap "spark-drv-d6b44b925e4b562a-conf-map" not found, which might be causing this issue ? 

```
34m         Normal    SparkApplicationDeleted        sparkapplication/structured-streaming-350-1728158512        SparkApplication structured-streaming-350-1728158512 was deleted
29m         Normal    Scheduled                      pod/structured-streaming-350-1728158844-driver              Successfully assigned so350/structured-streaming-350-1728158844-driver to gke-versa-kafka-poc--versa-kafka-poc--bbe7876b-4w9p
29m         Warning   FailedMount                    pod/structured-streaming-350-1728158844-driver              MountVolume.SetUp failed for volume "spark-conf-volume-driver" : configmap "spark-drv-d6b44b925e4b562a-conf-map" not found
29m         Normal    Pulling                        pod/structured-streaming-350-1728158844-driver              Pulling image "us-east1-docker.pkg.dev/versa-kafka-poc/spark-job-repo/ss-main-so350:3.5.0"
29m         Normal    Pulled                         pod/structured-streaming-350-1728158844-driver              Successfully pulled image "us-east1-docker.pkg.dev/versa-kafka-poc/spark-job-repo/ss-main-so350:3.5.0" in 291ms (291ms including waiting). Image size: 1301216396 bytes.
29m         Normal    Created                        pod/structured-streaming-350-1728158844-driver              Created container spark-kubernetes-driver
29m         Normal    Started                        pod/structured-streaming-350-1728158844-driver              Started container spark-kubernetes-driver
28m         Normal    Scheduled                      pod/structured-streaming-350-1728158844-driver              Successfully assigned so350/structured-streaming-350-1728158844-driver to gke-versa-kafka-poc--versa-kafka-poc--bbe7876b-4w9p
28m         Warning   FailedMount                    pod/structured-streaming-350-1728158844-driver              MountVolume.SetUp failed for volume "spark-conf-volume-driver" : configmap "spark-drv-a3cb9b925e4c2f1b-conf-map" not found
28m         Normal    Pulling                        pod/structured-streaming-350-1728158844-driver              Pulling image "us-east1-docker.pkg.dev/versa-kafka-poc/spark-job-repo/ss-main-so350:3.5.0"
28m         Normal    Pulled                         pod/structured-streaming-350-1728158844-driver              Successfully pulled image "us-east1-docker.pkg.dev/versa-kafka-poc/spark-job-repo/ss-main-so350:3.5.0" in 255ms (255ms including waiting). Image size: 1301216396 bytes.
28m         Normal    Created                        pod/structured-streaming-350-1728158844-driver              Created container spark-kubernetes-driver
28m         Normal    Started                        pod/structured-streaming-350-1728158844-driver              Started container spark-kubernetes-driver
27m         Normal    Scheduled                      pod/structured-streaming-350-1728158844-driver              Successfully assigned so350/structured-streaming-350-1728158844-driver to gke-versa-kafka-poc--versa-kafka-poc--bbe7876b-4w9p
27m         Warning   FailedMount                    pod/structured-streaming-350-1728158844-driver              MountVolume.SetUp failed for volume "spark-conf-volume-driver" : configmap "spark-drv-775201925e4d1a19-conf-map" not found
27m         Normal    Pulling                        pod/structured-streaming-350-1728158844-driver              Pulling image "us-east1-docker.pkg.dev/versa-kafka-poc/spark-job-repo/ss-main-so350:3.5.0
 

how to debug/fix this ?

tia!


- [ ] ✋ I have searched the open/closed issues and my issue is not listed.


## Environment & Versions

- Spark Operator App version: spark-operator-2.0.1 
- Helm Chart Version: 
- Kubernetes Version: 1.3
- Apache Spark version: 3.5.0
