### ISSUE TITLE
kubeflow spark operator & SparkHistoryService on k8s - spark driver/executor logs not showing up Spark History Server

### ISSUE THREAD

**Issue by karanalang** [kubeflow/spark-operator#2280]
- [ ] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I have kubeflow spark operator installed on GKE (in namespace - so350), as well as Spark History Server installed on GKE in namespace shs-350. The spark job is launched in a separate names - spark-apps.

When i launch the spark job, it runs fine and i'm able to see the job details in the Spark History server UI. The Spark History Server is configured to have the events stored in GCP storage bucket.

While the events are getting stored, the worker & executor logs are not getting stored in the strage bucket and hence not showing up in the History Server UI. i.e. the stderr/etdout links are not enabled on the Spark History Server UI.

How do i enable storing the worker/executor logs on GCP bucket ? Do i need to install fluentbit ot fluentd to collect the logs from k8s pods & store in the storage bucket ?

Any inputs on this ?

tia!

Pls note : to enable the spark events to flow into GCP storage bucket, CM is created as shown below to update the spark-defaults.conf

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-history-server-conf
  namespace: shs-350
data:
  spark-defaults.conf: |
    spark.history.fs.logDirectory=gs://<storage-bucket>/spark-events
    spark.hadoop.google.cloud.auth.service.account.enable=true
    spark.hadoop.google.cloud.auth.service.account.json.keyfile=/etc/secrets/spark-gcs-key.json
    
```

In the spark job yaml, following configuration is done :

```
"spark.eventLog.enabled": "true"
"spark.eventLog.dir": "gs://<storage-bucket>/spark-events"
```
