### ISSUE TITLE
[BUG] Internal error occurred: failed calling webhook...Address is not allowed

### ISSUE THREAD

**Issue by BCantos17** [kubeflow/spark-operator#2281]
## Description
I have the Spark Operator Controller installed along with the webhook on my EKS cluster via helm chart with no errors but as I am trying to submit a SparkApplication manifest it fails to submit

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]
 spark-app.yaml
```yaml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: my-spark-app
  namespace: spark
spec:
  driver:
    annotations:
      karpenter.sh/do-not-disrupt: 'true'
    coreLimit: '8'
    coreRequest: '8'
    cores: 8
    javaOptions: '-Dlog4j2.configurationFile=/opt/spark/conf/log4j2.xml'
    labels:
      version: 3.5.1
    memory: 20G
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
    serviceAccount: spark-app
    volumeMounts:
      - mountPath: /opt/spark/conf
        name: log4j2-xml
  executor:
    annotations:
      karpenter.sh/do-not-disrupt: 'true'
    coreLimit: '8'
    coreRequest: '8'
    cores: 8
    deleteOnTermination: false
    instances: 29
    javaOptions: '-Dlog4j2.configurationFile=/opt/spark/conf/log4j2.xml'
    labels:
      version: 3.5.1
    memory: 20G
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
    serviceAccount: spark-app
    volumeMounts:
      - mountPath: /opt/spark/conf
        name: log4j2-xml
  hadoopConf:
    fs.s3.aws.credentials.provider: com.amazonaws.auth.WebIdentityTokenCredentialsProvider
    fs.s3.aws.credentials.provider.web.identity.token.file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    fs.s3.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
    fs.s3a.aws.credentials.provider: com.amazonaws.auth.WebIdentityTokenCredentialsProvider
    fs.s3a.aws.credentials.provider.web.identity.token.file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    fs.s3a.impl: org.apache.hadoop.fs.s3a.S3AFileSystem
  image: my-company-domain/image-name:1.0.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - secret
  mainApplicationFile: local:////opt/spark/work-dir/__main__.py
  mode: cluster
  pythonVersion: '3'
  restartPolicy:
    type: Never
  sparkConf:
    spark.dynamicAllocation.executorIdleTimeout: 600s
    spark.eventLog.dir: s3a://bucket-for-logs/logs
    spark.eventLog.enabled: 'true'
    spark.history.fs.logDirectory: s3a://bucket-for-logs/logs
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path: /opt/spark/shuffle
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly: 'false'
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.options.claimName: OnDemand
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit: 25Gi
    spark.kubernetes.driver.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass: io2-storage-class
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.path: /opt/spark/shuffle
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.mount.readOnly: 'false'
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.claimName: OnDemand
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.sizeLimit: 25Gi
    spark.kubernetes.executor.volumes.persistentVolumeClaim.spark-local-dir-1.options.storageClass: io2-storage-class
    spark.local.dir: /opt/spark/shuffle
    spark.serializer: org.apache.spark.serializer.KryoSerializer
  sparkVersion: 3.5.1
  timeToLiveSeconds: 600
  type: Python
  volumes:
    - configMap:
        name: log4j2-xml
      name: log4j2-xml
```

Values.yaml
```yaml
# https://github.com/kubeflow/spark-operator/blob/v2.0.2/charts/spark-operator-chart/values.yaml
nameOverride: ${helm_name}
fullnameOverride: ${helm_name}

image:
  registry: my-company-domain
  repository: spark-operator
  pullPolicy: IfNotPresent
  tag: "v2.0.2"
  pullSecrets: 
    - name: secret

controller:
  serviceAccount:
    create: false
    name: "${spark_operator}"
    annotations:
      eks.amazonaws.com/role-arn: "${operator_role_arn}"
    volumes:
      - name: log4j2-xml
        configMap:
            name: log4j2-xml
    volumeMounts:
      - mountPath: /opt/spark/conf
        name: log4j2-xml
  
spark:
  jobNamespaces:
  - spark
  serviceAccount:
    create: false
    name: "${spark_app}"
    annotations:
      eks.amazonaws.com/role-arn: "${app_role_arn}"

prometheus:
  metrics:
    enable: false
```

run `kubectl apply -f spark-app.yaml`

## Expected behavior

Expected Spark App to run with the proper configurations. Note that I have a podSecurityContext and I attempted to add an affinity but these things dont get added without the webhook which is why I need this enabled

## Actual behavior

```
Error from server (InternalError): error when creating "spark-app.yaml": Internal error occurred: failed calling webhook "mutate-sparkoperator-k8s-io-v1beta2-sparkapplication.sparkoperator.k8s.io": failed to call webhook: Post "https://spark-operator-webhook-svc.spark.svc:9433/mutate-sparkoperator-k8s-io-v1beta2-sparkapplication?timeout=10s": Address is not allowed
```

## Environment & Versions

- Spark Operator App version: 2.0.2
- Helm Chart Version: 2.0.2
- Kubernetes Version: 1.29
- Apache Spark version: 3.5.0

## Additional context

I attempted to create a network policy allowing pods with the `spark-operator` label access but it didn't help. Also ran a couple of commands with the following outputs

```
wget --spider https://spark-operator-webhook-svc.spark.svc:9443
Spider mode enabled. Check if remote file exists.
--2024-10-23 22:47:51--  https://spark-operator-webhook-svc.spark.svc:9443/
Resolving spark-operator-webhook-svc.spark.svc (spark-operator-webhook-svc.spark.svc)... <IP-ADDRESS>
Connecting to spark-operator-webhook-svc.spark.svc (spark-operator-webhook-svc.spark.svc)|<IP-ADDRESS>|:9443... connected.
ERROR: The certificate of 'spark-operator-webhook-svc.spark.svc' is not trusted.
ERROR: The certificate of 'spark-operator-webhook-svc.spark.svc' doesn't have a known issuer.
The certificate's owner does not match hostname 'spark-operator-webhook-svc.spark.svc'
```

```
curl -k https://spark-operator-webhook-svc.spark.svc:9443
404 page not found
```

Under secrets in my EKS cluster, I see `spark-operator-webhook-certs` exists with ca-cert.pem, ca-key.pem, server-cert.pem, server-key.pem

**Comment by ChenYi015** [comment]
@BCantos17 I think the reason is the same as https://github.com/cert-manager/cert-manager/issues/3645.

**Comment by BCantos17** [comment]
So I deleted `spark-operator-webhook` which seems like the equivalent to `cert-manager-webhook` and on the surface it looks like it works but looking into it more I do not see some of the values I am trying to set. I modified the above Spark App specs to include an affinity which according to the documentation is supported but I do not see that in the Driver pod that gets spun up. I do not see the SecurityContext either. That link did provide some insight though.

Our cluster is running Calico and [here](https://cert-manager.io/docs/installation/compatibility/#aws-eks)  states that in order to make cert-manager work on an EKS cluster with Calico, we must set webhook.hostNetwork key to true. I am not the original maintainer of this cluster but I am assuming this is something to do be on my end and not on the Spark Operator? I just want to confirm before I go dig into a rabbit hole

**Comment by ChenYi015** [comment]
@BCantos17 

For now,  some fields of the Spark pods ( e.g. affinity, securityContext and volumeMount) are patched by the webhook, so it will not work if you delete the webhook.

Starting from version `v2.1.0-rc.0`, you can use pod templates (e.g. `.spec.driver.template` and `.spec.executor.template`) to customize almost everything with the Spark pods without a webhook.

**Comment by BCantos17** [comment]
Thanks @ChenYi015. For now I managed to get around this issue by specifying `spark.driver.podTemplate`. Appreciate the support and looking forward to v2.1.x

**Comment by josecsotomorales** [comment]
@ChenYi015 was testing `v2.1.0-rc.0` with the mutating webhook disabled, and using the new pod templates support, everything seems to be working ok except for `ownerReferences`, I don't see them being injected to pods making them invisible from tools like ArgoCD, the app runs fine, and I can see the service.. it has the `ownerReference` field properly injected, this only happens to the pods for some reason:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    sparkoperator.k8s.io/app-name: develop-app-qualytics-spark
    sparkoperator.k8s.io/submission-id: e5185dcc-bcb6-4f7f-b56a-bff99b2b52db
  name: develop-app-spark-ui-svc
  namespace: default
  ownerReferences:
    - apiVersion: sparkoperator.k8s.io/v1beta2
      blockOwnerDeletion: true
      controller: true
      kind: SparkApplication
      name: develop-app-spark
      uid: bc1b2fe7-502e-445a-9c5a-b198670cfadb
```
