### ISSUE TITLE
Unable to submit spark application with pod template

### ISSUE THREAD

**Issue by sharathchandramg** [kubeflow/spark-operator#2356]
I am trying to use SparkOperator on Azure Kubernetes Cluster. I am able to get the basic jobs working fine. I wanted to explore the option of having pod template. I see there are 2 ways to provide pod template.
1. Inline - https://github.com/kubeflow/spark-operator/blob/master/examples/spark-pi-pod-template.yaml
2. Using `sparkConf` and using ConfigMap

Unfortunately both are not working.

Using the example as in (1) gives me the error
```
Error from server (BadRequest): error when creating "examples/spark-pi-pod-template-1.yaml": SparkApplication in version "v1beta2" cannot be handled as a SparkApplication: strict decoding error: unknown field "spec.driver.template"
```

I have tried using the sparkconf option. The SparkApp definition is 

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "demo-pi-pod-template-1"
  namespace: demobox
  labels:
    app.kubernetes.io/name: demo-pi
    app.kubernetes.io/component: demo-pi
spec:
  type: Java
  mode: cluster
  image: spark:3.4.4
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: local:///opt/spark/examples/jars/spark-examples_2.12-3.4.4.jar
  sparkVersion: 3.4.4
  restartPolicy:
    type: OnFailure
  timeToLiveSeconds: 3600
  sparkConf:
    "spark.driver.extraJavaOptions": "-Dconfig.file=/demobox/anthub/etc/application.properties -Dlog4j.configurationFile=/demobox/anthub/etc/log4j2.properties -Dconfig.debug=true"
    "spark.executor.extraJavaOptions": "-Dconfig.file=/demobox/anthub/etc/application.properties -Dlog4j.configurationFile=/demobox/anthub/etc/log4j2.properties -Dconfig.debug=true"
    "spark.kubernetes.driver.podTemplateFile" : "/demobox/anthub/etc/spark_pod_template.yaml"
    "spark.kubernetes.executor.podTemplateFile" : "/demobox/anthub/etc/spark_pod_template.yaml"
    "spark.kubernetes.submission.waitAppCompletion": "false"
  arguments:
    - "10000"

  driver:
    serviceAccount: anthub
    cores: 1
    memory: 512m
    labels:
      version: "3.4.4"
    volumeMounts:
    - name: anthub-config
      mountPath: /demobox/anthub/etc
    - name: spark-pod-template
      mountPath: /etc/spark/templates
    tolerations:
    - key: "role"
      operator: "Equal"
      value: "compute"
      effect: "NoSchedule"
  executor:
    serviceAccount: anthub
    cores: 1
    instances: 1
    memory: 512m
    volumeMounts:
    - name: anthub-config
      mountPath: /demobox/anthub/etc
    tolerations:
    - key: "role"
      operator: "Equal"
      value: "compute"
      effect: "NoSchedule"

  volumes:
  - name: anthub-config
    configMap:
      name: anthub

```
On submitting the SparkApp I keep getting the error that file `/demobox/anthub/etc/spark_pod_template.yaml` is not found. 

However on inspecting the container, I can see the files mounted and read permissions for all the users. I am not sure why I can see the spark_pod_template.yaml within the container, but SparkApp is unable to find that ?

**The environment details are:**
Spark Operator Version : 2.1.0
Kubernetes Version : 1.30.6
