### ISSUE TITLE
it's not possible to set securityContext.seccompProfile in SparkApplication

### ISSUE THREAD

**Issue by gannulka** [kubeflow/spark-operator#2413]
### What happened?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

WIth the latest installed spark-operatot helm chart (v2.1.0) and activated webhook (by default) it's not possible to deploy SparkApplication (apiVersion: sparkoperator.k8s.io/v1beta2) with 
```
driver:
   securityContext:
       seccompProfile:
           type: RuntimeDefault

``` 
the same for 
```
executor:
   securityContext:
       seccompProfile:
           type: RuntimeDefault

```
Error is 
```
strict decoding error: unknown field "spec.driver.securityContext.seccompProfile"
```

spark-operator-webhook doesn't contain any errors or logs specific to this timestamp.

### Reproduction Code

Deploy SparkApplication with 

```
driver:
   securityContext:
       seccompProfile:
           type: RuntimeDefault

``` 
or

```
driver:
   podSecurityContext:
       seccompProfile:
           type: RuntimeDefault

``` 
or

```
executor:
   securityContext:
       seccompProfile:
           type: RuntimeDefault

``` 
or

```
executor:
   podSecurityContext:
       seccompProfile:
           type: RuntimeDefault

``` 

### Expected behavior

Webhook should allow this field according to documentation https://github.com/kubeflow/spark-operator/blob/master/docs/api-docs.md#sparkoperator.k8s.io/v1beta2.SparkPodSpec 

### Actual behavior

Error is 
```
strict decoding error: unknown field "spec.driver.securityContext.seccompProfile"
```

### Environment & Versions

- Kubernetes Version: 1.30
- Spark Operator Version: 2.1.0
- Apache Spark Version: 3.2.2

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍
