### ISSUE TITLE
Controller uiIngress and uiService not working .

### ISSUE THREAD

**Issue by Taymindis** [kubeflow/spark-operator#2565]
### What happened?

has enable the config 

```yaml
controller:
  uiService:
    # -- Specifies whether to create service for Spark web UI.
    enable: true

  uiIngress:
    # -- Specifies whether to create ingress for Spark web UI.
    # `controller.uiService.enable` must be `true` to enable ingress.
    enable: true
    # -- Ingress URL format.
    # Required if `controller.uiIngress.enable` is true.
    urlFormat: "sparkui.com"
    # -- Optionally set the ingressClassName.
    ingressClassName: "nginx"
```

ingress not showing spark ingress, and service only show `spark-operator-webhook-svc`

### Environment & Versions

- Kubernetes Version:
- Spark Operator Version:
- Apache Spark Version:

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍
