### ISSUE TITLE
SparkApplication driverSpec volumeMount not being created...

### ISSUE THREAD

**Issue by Taymindis** [kubeflow/spark-operator#2575]
### What happened?

the `spark-vol` never been mounted 

```yaml
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-kafka-stream
  # namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.5
  imagePullPolicy: IfNotPresent
          ....
  volumes:
  - name: ivy-cache
    persistentVolumeClaim:
      claimName: spark-ivy-cache-shared
  arguments:
  - "true"
  sparkVersion: 3.5.5
  sparkConf:
      ....
  deps:
    repositories:
      - https://packages.confluent.io/maven
    packages:
       .....
  driver:
    volumeMounts:
    - name: spark-vol
      mountPath: /opt/spark/work-dir/apps
```

<img width="736" alt="Image" src="https://github.com/user-attachments/assets/37d18cea-ae2d-483f-9fa4-e69ecd69284e" />

<img width="1428" alt="Image" src="https://github.com/user-attachments/assets/f58c29d9-597e-4d93-bdbb-ced9008aa41e" />

### Environment & Versions

- Kubernetes Version:
- Spark Operator Version:
- Apache Spark Version:

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍
