### ISSUE TITLE
SparkApplication Monitoring Configuration misleading/confusing

### ISSUE THREAD

**Issue by rolandjohann** [kubeflow/spark-operator#560]
Configure monitoring for spark applications is slightly confusing.

With this we setup monitoring:
```yaml
  monitoring:
    metricsProperties: |
      *.sink......
      *.source....
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
      port: 8090
```
As far as I can see all properties at `spec.monitoring` are prometheus related. Even if we don't specify `spec.monitoring.prometheus` the value of `spec.monitoring.monitoringProperties` won't be passed to the pods as defined in the code below.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/4439d47e47c9e282149b8c52591eff72d2bdd2bc/pkg/controller/sparkapplication/controller.go#L599-L603

So properties set at `spec.monitoring.prometheus` influence `spec.monitoring.monitoringProperties` which is slightly confusing.

Currently I'm happy that `spec.monitoring.monitoringProperties` will be omitted if we don't configure it because I setup prometheus push gateweay monitoring and therefore need to setup monitoring.properties by myself at another place.

Regarding `spec.monitoring.monitoringProperties` I suggest to use default content provided by spark operator when `spec.monitoring.prometheus` is in use with the possibility to overwrite it (current behavior) but also render `spec.monitoring.monitoringProperties` when prometheus is not in use (not current behavior) because of

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/4439d47e47c9e282149b8c52591eff72d2bdd2bc/pkg/controller/sparkapplication/controller.go#L599-L603

In addition `spec.monitoring.exposeDriverMetrics` and `spec.monitoring.exposeExecutorMetrics` are exclusively prometheus related and maybe should be moved to `spec.monitoring.prometheus` (IMHO more obvious grouping of config properties) including opening the relevant ports at the pods via webhook - but that's a different story.

What do you think?
