### ISSUE TITLE
Multiple ways to specify Spark configurations causing duplicate spark-submit args

### ISSUE THREAD

**Issue by michaeljmarshall** [kubeflow/spark-operator#626]
There are two ways to set many of the spark-submit configurations.  The current spark submission logic found in `submission.go` does not do any de-duplication of these configurations, which leads to potentially undefined behavior.

For example, suppose you were to apply the following `yaml` file:
```
apiVersion: "sparkoperator.k8s.io/v1beta1"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v2.4.0"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar"
  sparkVersion: "2.4.0"
  sparkConf:
    "spark.driver.cores": "2"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 2.4.0
    serviceAccount: cautious-chicken-spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```

Because the `spec.driver.cores` field maps to the spark configuration `spark.driver.cores` and there is no de-duplication nor a defined precedence, the spark operator passes the following arguments to spark-submit: 

```I0918 22:47:23.101329       9 submission.go:63] spark-submit arguments: [/opt/spark/bin/spark-submit --class org.apache.spark.examples.SparkPi --master k8s://https://10.96.0.1:443 --deploy-mode cluster --conf spark.kubernetes.namespace=default --conf spark.app.name=spark-pi --conf spark.kubernetes.driver.pod.name=spark-pi-driver --conf spark.kubernetes.container.image=gcr.io/spark-operator/spark:v2.4.0 --conf spark.kubernetes.container.image.pullPolicy=Always --conf spark.kubernetes.submission.waitAppCompletion=false --conf spark.driver.cores=2 --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/app-name=spark-pi --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.kubernetes.driver.label.sparkoperator.k8s.io/submission-id=47c67adb-f110-4b87-984a-a2543e1c8c0d --conf spark.driver.cores=1.000000 --conf spark.kubernetes.driver.limit.cores=1200m --conf spark.driver.memory=512m --conf spark.kubernetes.authenticate.driver.serviceAccountName=cautious-chicken-spark --conf spark.kubernetes.driver.label.version=2.4.0 --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/app-name=spark-pi --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/launched-by-spark-operator=true --conf spark.kubernetes.executor.label.sparkoperator.k8s.io/submission-id=47c67adb-f110-4b87-984a-a2543e1c8c0d --conf spark.executor.instances=1 --conf spark.executor.cores=1 --conf spark.executor.memory=512m --conf spark.kubernetes.executor.label.version=2.4.0 local:///opt/spark/examples/jars/spark-examples_2.11-2.4.0.jar]```

Notice that the `spark.driver.cores` configuration is passed to spark-submit twice. While `spark-submit` does not fail here, I think the spark-operator should have an explicit precedence of fields to prevent this duplication and ensure a straightforward implemenation.

While it seems easier for new users to give the `sparkConf` map the highest precedence, I think the ordering should probably be first the `spec` and then the `sparkConf` map. I haven't worked with the Mutating Admission Webhook, but I assume the choice here will have consequences for the webhook because if you want to enforce some type of default field, you'll want to specify it in the field that has the highest precedence.

Note: I tested this issue using the `v1beta1` version.

The implementation shouldn't be too complicated, but I'd like some consensus before I submit a PR.

Let me know if you have any questions. Thanks.
