### ISSUE TITLE
'SparkApplicationSpecUpdateFailed' failed to process spec update for SparkApplication

### ISSUE THREAD

**Issue by kumud-pe** [kubeflow/spark-operator#698]
I am running on K8s 1.10.13 using spark operator version v1beta2-1.0.1-2.4.4.
Installed operator on the cluster using
```
helm install incubator/sparkoperator --namespace spark-test --set sparkJobNamespace=spark-test,enableWebhook=true,enableMetrics=false --name so
```
Here is the spark application that I am planning to run.
```
apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-scala-test
  namespace: spark-test
spec:
  type: Scala
  sparkVersion: 2.4.4
  mode: cluster
  image: test/test-skull-spark-structured-streaming:v2
  mainClass: SparkScalaTest
  mainApplicationFile: local:///opt/spark/work-dir/spark-scala-test-project_2.11-1.0.jar
  arguments:
    - localhost
    - "9999"
  sparkConf:
    "spark.ui.port": "4045"
  driver:
    cores: 1
    coreLimit: 1000m
    memory: 1g
    memoryOverhead: 256m
    labels:
      version: 2.4.4
    serviceAccount: so-spark
  executor:
    cores: 1
    coreRequest: 100m
    coreLimit: 300m
    instances: 1
    memory: 1g
    memoryOverhead: 256m
    labels:
      version: 2.4.4
  restartPolicy:
    type: Always
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  timeToLiveSeconds: 3600

```
When I made any change on this and `kubectl apply` again. I get the following error in the logs as well as on the events in `kubectl describe`
```
Warning  SparkApplicationSpecUpdateFailed  30m   spark-operator  failed to process spec update for SparkApplication spark-scala-test: the server could not find the requested resource (put sparkapplications.sparkoperator.k8s.io spark-scala-test)
```
Am I missing something here?
