### ISSUE TITLE
ScheduledSparkApplication stopped creating new SparkApplication instances after failure

### ISSUE THREAD

**Issue by duongnt** [kubeflow/spark-operator#787]
I have a ScheduledSparkApplication instance that was running well. However at some point, it stopped creating new SparkApplication instance. Here are some relevant excerpt of the log:

```I 2020-02-03T04:43:42.570512Z Syncing ScheduledSparkApplication spark-operator/spark-app 
I 2020-02-03T04:43:42.570749Z Next run of ScheduledSparkApplication spark-operator/spark-app is due, creating a new SparkApplication instance 
I 2020-02-03T04:43:42.597566Z SparkApplication spark-operator/spark-app-1580705022570653626 was added, enqueueing it for submission 
I 2020-02-03T04:43:42.597779Z Starting processing key: "spark-operator/spark-app-1580705022570653626" 
I 2020-02-03T04:43:42.598127Z Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-operator", Name:"spark-app-1580705022570653626", UID:"c12a53b7-463f-11ea-b43e-42010a4c005b", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"116694103", FieldPath:""}): type: 'Normal' reason: 'SparkApplicationAdded' SparkApplication spark-app-1580705022570653626 was added, enqueuing it for submission 
I 2020-02-03T04:43:42.598367Z spark-submit arguments: [/opt/spark/bin/spark-submit --class sparkApp] 
I 2020-02-03T04:43:42.625613Z Syncing ScheduledSparkApplication spark-operator/spark-app 
I 2020-02-03T04:43:46.286911Z Pod spark-app-1580705022570653626-driver in namespace spark-operator is subject to mutation 
I 2020-02-03T04:43:46.299988Z Pod spark-app-1580705022570653626-driver added in namespace spark-operator. 
I 2020-02-03T04:43:46.319535Z Pod spark-app-1580705022570653626-driver updated in namespace spark-operator. 
I 2020-02-03T04:43:46.341239Z Pod spark-app-1580705022570653626-driver updated in namespace spark-operator. 
I 2020-02-03T04:43:46.857410Z Pod spark-app-1580705022570653626-driver updated in namespace spark-operator. 
I 2020-02-03T04:43:46.865382Z Pod spark-app-1580705022570653626-driver deleted in namespace spark-operator. 
W 2020-02-03T04:43:46.960530Z trying to resubmit an already submitted SparkApplication spark-operator/spark-app-1580705022570653626 
I 2020-02-03T04:43:46.960574Z Trying to update SparkApplication spark-operator/spark-app-1580705022570653626, from: [{  0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } { } map[] 0 0}] to [{  0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC { 0    } { } map[] 0 0}] 
  undefined
I 2020-02-03T04:43:46.960830Z Ending processing key: "spark-operator/spark-app-1580705022570653626" 
I 2020-02-03T04:44:12.570804Z Syncing ScheduledSparkApplication spark-operator/spark-app 
I 2020-02-03T04:44:42.571031Z Syncing ScheduledSparkApplication spark-operator/spark-app 
```

The status of ScheduledSparkApplication looks like this:
```
status:
  lastRun: "2020-02-03T04:43:42Z"
  lastRunName: spark-app-1580705022570653626
  nextRun: "2020-02-03T04:48:42Z"
  pastFailedRunNames:
  - spark-app-1580686722390076571
  pastSuccessfulRunNames:
  - spark-app-1580704722567671035
  - spark-app-1580704422565140917
  - spark-app-1580704122562581879
  - spark-app-1580703822559473339
  - spark-app-1580703522556632453
  - spark-app-1580703222553982770
  - spark-app-1580702922551117600
  - spark-app-1580702622548623812
  - spark-app-1580702322546336470
  - spark-app-1580702022543189697
  scheduleState: Scheduled
```

So looks like the run `spark-app-1580705022570653626` is considered neither failed nor successful, and that blocks the next run from being started? I'm not sure why `spark-app-1580705022570653626` wasn't able to start either, but it definitely left the ScheduledSparkApplication deployment in a bad state.
