### ISSUE TITLE
Question: does executor needs checkpoint directory?

### ISSUE THREAD

**Issue by FloraZhang** [kubeflow/spark-operator#913]
Hi,

I have a question on configuring checkpoint directory for spark application chart. 

According to spark documentation https://spark.apache.org/docs/latest/streaming-programming-guide.html#checkpointing Spark needs distributed file system to store its checkpoint data so that in case of failure, it can recover from checkpoint directory. 

In spark application helm chart I have a checkpointlocation configuration:
```
spec:
   sparkConf:
     "spark.ui.port": "40450"
     "spark.sql.streaming.checkpointLocation": "file:///opt/checkpoint-data"
```
I created a checkpoint pvc and mount the volume for driver pod:
```
  volumes:
    - name: checkpoint-volume
      persistentVolumeClaim:
        claimName: checkpoint-pvc

driver:
    volumeMounts:
      - name: checkpoint-volume
        mountPath: "/opt/checkpoint-data"
```

In Spark Streaming Guide, it mentioned "Failed driver can be restarted from checkpoint information" and when executor failed, "Tasks and receivers restarted by Spark automatically, no config needed"

So my question is: does executor also needs this checkpoint directory for recovery? 

Thanks,
Wenjing
