### ISSUE TITLE
set correct SPARK_USER ENV when submit sparkapplications

### ISSUE THREAD

**Issue by camper42** [kubeflow/spark-operator#931]
https://github.com/apache/spark/commit/4b3fe3a9ccc8a4a8eb0d037d19cb07a8a288e37a
start spark-3.0, driver & executor will configure with `SPARK_USER` env
> Finally, the new code always sets SPARK_USER in the driver and
executor pods. This is in line with how other resource managers
behave: the submitting user reflects which user will access
Hadoop services in the app. (With kerberos, that's overridden
by the logged in user.) That user is unrelated to the OS user
the app is running as inside the containers.

in `org.apache.spark.util.Utils#getCurrentUserName`, `SPARK_USER` env has higher priotiry than `runAsUser`

and spark will use this to interact with Hadoop
`org.apache.spark.deploy.SparkHadoopUtil#createSparkUser`

---

our problem:
 
1. all image build with `spark_uid=5089`
2. a stream application `runAsUser=3631`
3. task failed due to `org.apache.hadoop.security.AccessControlException: Permission denied: user=5089, access=WRITE, inode="/user/camper42/streaming_checkpoint/query2":camper42:supergroup:drwxr-xr-x` (user camper42's uid is 3631)

**Comment by liyinan926** [comment]
Not sure what you are asking for here. Can you elaborate what feature/fix/change you are thinking of?

**Comment by camper42** [comment]
spark-operator:
- username: 5089
- uid: 5089

spark-application (use `serucityContext.runAsUser: 3631` & mount `/etc/password`):
- username: camper42
- uid: 3631

---

Problem:

1. spark-operator submit app (spark-submit process uid 5089)
2. driver pod start, uid 3631, username camper42, but has environment variable `SPARK_USER=5089`, due to apache/spark@4b3fe3a
3. executor pod start, uid 3631, username campee42, but has environment variable `SPARK_USER=5089`, due to apache/spark@4b3fe3a
4. executor write checkpoint to HDFS with username `5089` not `camper42` as expected.(`SPARK_USEER` priority higher than container uid)
5. permissioin denied, task failed.

---

current fix our use:
add below to driver pod spec
```
env:
  - name: SPARK_USER
    value: camper42
```

and driver pod will has two env named `SPARK_USER` like:
```
    env:
    - name: SPARK_USER
      value: "5089"
    - name: SPARK_APPLICATION_ID
      value: spark-44baec237ea2422da98eb877bcaeb82d
    - name: SPARK_DRIVER_BIND_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: PYSPARK_MAJOR_PYTHON_VERSION
      value: "3"
    - name: SPARK_LOCAL_DIRS
      value: /var/data/spark-ce8f601d-07b3-42db-a0d9-9f9fc04b3b03
    - name: SPARK_CONF_DIR
      value: /opt/spark/conf
    - name: HADOOP_CONF_DIR
      value: /etc/hadoop/conf
    - name: SPARK_USER
      value: camper42
```

---

> Not sure what you are asking for here. Can you elaborate what feature/fix/change you are thinking of?

maybe add `.spec.sparkUser` to CRD?
and spark-operator run submit like: `env=<.spec.sparkUser> spark-submit` to set correct SPARK_USER environment variable in application

I'm not sure it will be considered as a bug or a missing feature
