### ISSUE TITLE
Init Containers cause service account to not be properly mounted to driver during spark-submit

### ISSUE THREAD

**Issue by thealmightygrant** [kubeflow/spark-operator#958]
We are using the latest release of the spark operator: `v1beta2-1.1.2-2.4.5`.

I believe that this is related to #537. I am adding an initContainer onto the driver pod like this:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: some-spark-job
  #TODO: move everything to the spark namespace eventually to match things up
  namespace: spark-structured-streaming
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/some-spark-job"
  imagePullPolicy: Always
  mainClass: "someSparkJob.Main"
  mainApplicationFile: "local:///opt/spark/jars/spark-job.jar"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Always
    onFailureRetryInterval: 10
    onSubmissionFailureRetryInterval: 10
  driver:
    serviceAccount: default
    cores: 2
    memory: "6g"
    initContainers:
    - name: clear-spark-data
      image: "debian:latest"
      command: ["bash"]
      args: ["-c", "while true; do sleep 5; done"]
  executor:
    cores: 1
    instances: 5
    memory: "6g"
```
This results in some very strange operator logs:
```
"errorMessage": "failed to run spark-submit for SparkApplication spark-structured-streaming/some-spark-job: log4j:WARN No appenders could be found for logger (io.fabric8.kubernetes.client.Config).\nlog4j:WARN Please initialize the log4j system properly.\nlog4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.\nUsing Spark's default log4j profile: org/apache/spark/log4j-defaults.properties\nException in thread \"main\" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.253.94.1/api/v1/namespaces/spark-structured-streaming/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods \"some-spark-job-driver\" is forbidden: unable to validate against any pod security policy: []...
```
This only happens when I add one or more `initContainers`. Otherwise, this job functions normally and is processed correctly. I am wondering if there is some kind of race condition happening here? We are on k8s 1.14, so it is perhaps related to [this](https://github.com/kubernetes/kubernetes/issues/73291).

**Comment by thealmightygrant** [comment]
For extra context, here are the associated `role` and `rolebinding` for the default service account in this namespace:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  creationTimestamp: "2020-03-06T00:13:22Z"
  labels:
    app.kubernetes.io/instance: spark-dev
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.7.1
  name: spark-role-binding
  namespace: spark-structured-streaming
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: spark-structured-streaming
```

And the role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
  creationTimestamp: "2020-03-03T20:39:18Z"
  labels:
    app.kubernetes.io/instance: spark-dev
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: sparkoperator
    helm.sh/chart: sparkoperator-0.7.1-etsy-2
  name: spark-role
  namespace: spark-structured-streaming
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
```
