### ISSUE TITLE
Does RAPIDS Accelerator support

### ISSUE THREAD

**Issue by silenceli** [kubeflow/spark-operator#967]
Spark 3.0.0 support [RAPIDS Accelerator](https://github.com/nvidia/spark-rapids) which can provides a set of plugins for Apache Spark that leverage GPUs to accelerate processing via the RAPIDS libraries and UCX.

Do you have any plans to support this feature?

Look forward to your reply, thx!

**Comment by silenceli** [comment]
I try above, It works

```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "docker-registry.qiyi.virtual/jarvis-image/spark-with-rapids:3.0.0"
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar"
  sparkConf:
    "spark.plugins": "com.nvidia.spark.SQLPlugin"
    "spark.executor.resource.gpu.discoveryScript": "/opt/sparkRapidsPlugin/getGpusResources.sh"
    "spark.executor.resource.gpu.vendor": "nvidia.com"
    "spark.driver.resource.gpu.discoveryScript": "/opt/sparkRapidsPlugin/getGpusResources.sh"
    "spark.driver.resource.gpu.vendor": "nvidia.com"
    "spark.rapids.sql.concurrentGpuTasks": "1"
    "spark.driver.resource.gpu.amount": "1"
    "spark.task.resource.gpu.amount": "1"
    "spark.executor.resource.gpu.amount": "1"
  ImagePullPolicy: IfNotPresent
  sparkVersion: "3.0.0"
  deps:
    jars:
      - local:///opt/sparkRapidsPlugin/cudf-0.14-cuda10-1.jar
      - local:///opt/sparkRapidsPlugin/rapids-4-spark_2.12-0.1.0.jar
    files:
      - local:///opt/sparkRapidsPlugin/getGpusResources.sh
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    gpu:
      name: "nvidia.com/gpu"
      quantity: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    gpu:
      name: "nvidia.com/gpu"
      quantity: 1
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
```
